// data_y.js
const devicesy = [
{ device: "Y17", comment: "이더넷  리셋 SIG", rtb: "" },
{ device: "Y0A0", comment: "Main    운전준비S/W Lamp", rtb: "" },
{ device: "Y0A1", comment: "Main    자동운전SW Lamp", rtb: "" },
{ device: "Y0A2", comment: "Main    자동정지SW Lamp", rtb: "" },
{ device: "Y0A3", comment: "MAIN:   09ST:   비상정지램프", rtb: "" },
{ device: "Y0A4", comment: "MAIN:   19ST:   비상정지램프", rtb: "" },
{ device: "Y0A5", comment: "MAIN:   29ST:   비상정지램프", rtb: "" },
{ device: "Y0A6", comment: "MAIN:   40ST:   비상정지램프", rtb: "" },
{ device: "Y0A7", comment: "MAIN:   60ST:   비상정지램프", rtb: "" },
{ device: "Y0A8", comment: "MAIN:   63ST:   비상정지램프", rtb: "" },
{ device: "Y0A9", comment: "MAIN:   76ST:   비상정지램프", rtb: "" },
{ device: "Y0AA", comment: "MAIN:   85ST:   비상정지램프", rtb: "" },
{ device: "Y0AC", comment: "Panel   경경등  '적'", rtb: "" },
{ device: "Y0AD", comment: "Panel   경경등  '황'", rtb: "" },
{ device: "Y0AE", comment: "PANEL   경광등  '녹'", rtb: "" },
{ device: "Y0AF", comment: "PANEL   BUZZER", rtb: "" },
{ device: "Y0B0", comment: "제어전원ON      (LAMP)", rtb: "" },
{ device: "Y0B1", comment: "자동운전ON      (LAMP)", rtb: "" },
{ device: "Y0B2", comment: "PLC Low Battery", rtb: "" },
{ device: "Y0B3", comment: "공압정상(LAMP)", rtb: "" },
{ device: "Y0B4", comment: "각공정  수동모드SQ", rtb: "" },
{ device: "Y0B5", comment: "OP:01   MODE    자동", rtb: "" },
{ device: "Y0B6", comment: "OP:01   MODE    수동", rtb: "" },
{ device: "Y0B7", comment: "Main    Spare   Lamp", rtb: "" },
{ device: "Y0B8", comment: "TOTAL   비상정지(Lamp)", rtb: "" },
{ device: "Y0B9", comment: "Total   Motor   과부하  (Lamp)", rtb: "" },
{ device: "Y0BA", comment: "Total    LS 이상 (LAMP)", rtb: "" },
{ device: "Y0BB", comment: "Main    Panel   CP Trip", rtb: "" },
{ device: "Y0BC", comment: "OP      CP Trip (Lamp)", rtb: "" },
{ device: "Y0BD", comment: "Remote  Box CP  Trip    (Lamp)", rtb: "" },
{ device: "Y0BE", comment: "Main    Spare   (Lamp)", rtb: "" },
{ device: "Y0BF", comment: "3st인타운서열작업완료", rtb: "" },
{ device: "Y0C0", comment: "PANEL   01:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C1", comment: "PANEL   02:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C2", comment: "PANEL   03:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C3", comment: "PANEL   04:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C4", comment: "PANEL   05:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C5", comment: "PANEL   06:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C6", comment: "PANEL   07:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C7", comment: "PANEL   08:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C8", comment: "PANEL   09:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0C9", comment: "PANEL   10:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0CA", comment: "PANEL   11:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0CB", comment: "PANEL   12:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0CC", comment: "PANEL   13:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0CD", comment: "PANEL   14:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0CE", comment: "PANEL   15:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0CF", comment: "PANEL   16:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D0", comment: "PANEL   17:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D1", comment: "PANEL   18:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D2", comment: "PANEL   19:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D3", comment: "PANEL   20:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D4", comment: "PANEL   21:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D5", comment: "PANEL   22:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D6", comment: "PANEL   23:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D7", comment: "PANEL   24:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D8", comment: "PANEL   25:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0D9", comment: "PANEL   26:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0DA", comment: "PANEL   27:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0DB", comment: "PANEL   28:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0DC", comment: "PANEL   29:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0DD", comment: "PANEL   30:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0DE", comment: "PANEL   31:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0DF", comment: "PANEL   32:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E0", comment: "PANEL   33:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E1", comment: "PANEL   34:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E2", comment: "PANEL   35:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E3", comment: "PANEL   36:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E4", comment: "PANEL   37:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E5", comment: "PANEL   38:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E6", comment: "PANEL   39:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E7", comment: "PANEL   40:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E8", comment: "PANEL   41:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0E9", comment: "PANEL   42:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0EA", comment: "PANEL   43:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0EB", comment: "PANEL   44:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0EC", comment: "PANEL   45:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0ED", comment: "PANEL   46:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0EE", comment: "PANEL   47:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0EF", comment: "PANEL   48:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F0", comment: "PANEL   49:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F1", comment: "PANEL   50:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F2", comment: "PANEL   51:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F3", comment: "PANEL   52:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F4", comment: "PANEL   53:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F5", comment: "PANEL   54:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F6", comment: "PANEL   55:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F7", comment: "PANEL   56:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F8", comment: "PANEL   57:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0F9", comment: "PANEL   58:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0FA", comment: "PANEL   59:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0FB", comment: "PANEL   60:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0FC", comment: "PANEL   61:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0FD", comment: "PANEL   62:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0FE", comment: "PANEL   63:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y0FF", comment: "PANEL   64:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y100", comment: "PANEL   65:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y101", comment: "PANEL   66:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y102", comment: "PANEL   67:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y103", comment: "PANEL   68:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y104", comment: "PANEL   69:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y105", comment: "PANEL   70:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y106", comment: "PANEL   71:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y107", comment: "PANEL   72:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y108", comment: "PANEL   73:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y109", comment: "PANEL   74:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y10A", comment: "PANEL   75:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y10B", comment: "PANEL   76:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y10C", comment: "PANEL   77:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y10D", comment: "PANEL   78:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y10E", comment: "PANEL   79:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y10F", comment: "PANEL   80:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y110", comment: "PANEL   81:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y111", comment: "PANEL   82:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y112", comment: "PANEL   83:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y113", comment: "PANEL   84:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y114", comment: "PANEL   85:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y115", comment: "PANEL   86:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y116", comment: "PANEL   87:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y117", comment: "PANEL   88:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y118", comment: "PANEL   89:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y119", comment: "PANEL   90:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y11A", comment: "PANEL   91:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y11B", comment: "PANEL   92:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y11C", comment: "PANEL   93:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y11D", comment: "PANEL   94:ST   ERROR   (LAMP)", rtb: "" },
{ device: "Y11E", comment: "MAIN:   52ST:   비상정지램프", rtb: "" },
{ device: "Y11F", comment: "MAIN:   R-11ST:   비상정지램프", rtb: "" },
{ device: "Y120", comment: "01ST:   D/V 모터정방향  모터출력", rtb: "" },
{ device: "Y121", comment: "01ST:   D/V 모터역방향  모터출력", rtb: "" },
{ device: "Y122", comment: "46ST:   DIVERTER모터 ON 기동출력", rtb: "" },
{ device: "Y123", comment: "MAIN    C/V_04  INV 'A' M1 MC", rtb: "" },
{ device: "Y124", comment: "MAIN    C/V_04  INV 'A' M2 MC", rtb: "" },
{ device: "Y125", comment: "MAIN    C/V_02  모터 'A'기동출력", rtb: "" },
{ device: "Y126", comment: "MAIN    C/V_02  모터 'B'기동출력", rtb: "" },
{ device: "Y127", comment: "48ST:   DIVERTER모터 ON 기동출력", rtb: "" },
{ device: "Y128", comment: "88ST D/V모터    정회전  기동출력", rtb: "" },
{ device: "Y129", comment: "90ST:   DIVERTERMOTOR   기동출력", rtb: "" },
{ device: "Y12A", comment: "88ST:   D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y12B", comment: "90ST:   D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y12C", comment: "93ST:   D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y12D", comment: "MAIN    C/V_04  모터 'A'기동출력", rtb: "" },
{ device: "Y12E", comment: "MAIN    C/V_04  모터 'B'기동출력", rtb: "" },
{ device: "Y12F", comment: "REPAIR  C/V_01  모터 ON 기동출력", rtb: "" },
{ device: "Y130", comment: "R_02ST: D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y131", comment: "R_03ST: D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y132", comment: "REPAIR  C/V_02  모터 ON 기동출력", rtb: "" },
{ device: "Y133", comment: "R_06ST: D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y134", comment: "REPAIR  C/V_03  모터 ON 기동출력", rtb: "" },
{ device: "Y135", comment: "R_09ST: D/V 모터정회전  기동출력", rtb: "" },
{ device: "Y136", comment: "REPAIR  C/V_04  모터 ON 기동출력", rtb: "" },
{ device: "Y139", comment: "Main    Panel   Buzzer01", rtb: "" },
{ device: "Y13B", comment: "공정비상정지멜로디", rtb: "" },
{ device: "Y200", comment: "임시접점출력", rtb: "" },
{ device: "Y320", comment: "OP:01   자동운전SW Lamp", rtb: "" },
{ device: "Y321", comment: "OP:01   자동정지SW Lamp", rtb: "" },
{ device: "Y322", comment: "OP01:   수동    LAMP", rtb: "" },
{ device: "Y323", comment: "OP:01   Trouble Lamp", rtb: "" },
{ device: "Y324", comment: "OP:01   Motor   과부하  Lamp", rtb: "" },
{ device: "Y325", comment: "OP:01   비상정지Lamp", rtb: "" },
{ device: "Y332", comment: "OP1판넬  불량    리워크 배출알람", rtb: "" },
{ device: "Y333", comment: "OP1판넬 불량    리워크  입고알람", rtb: "" },
{ device: "Y33C", comment: "OP:01   경광등  '적'", rtb: "" },
{ device: "Y33D", comment: "OP:01   경광등  '황'", rtb: "" },
{ device: "Y33E", comment: "OP:01   경광등  '녹'", rtb: "" },
{ device: "Y33F", comment: "OP:01   Buzzer", rtb: "" },
{ device: "Y340", comment: "Main    Cycle   Time    1의 자리", rtb: "" },
{ device: "Y3A0", comment: "OP:02   자동운전SW Lamp", rtb: "" },
{ device: "Y3A1", comment: "OP:02   자동정지SW Lamp", rtb: "" },
{ device: "Y3A2", comment: "OP:02   수동    LAMP", rtb: "" },
{ device: "Y3A3", comment: "OP:02   LS&SOL  이상    LAMP", rtb: "" },
{ device: "Y3A4", comment: "OP:02   MOTOR   과부하  LAMP", rtb: "" },
{ device: "Y3A5", comment: "OP:02   비상정지LAMP", rtb: "" },
{ device: "Y3BC", comment: "OP:02   경광등  '적'    LAMP", rtb: "" },
{ device: "Y3BD", comment: "OP:02   경광등  '황'    LAMP", rtb: "" },
{ device: "Y3BE", comment: "OP:02   경광등  '녹'    LAMP", rtb: "" },
{ device: "Y3BF", comment: "OP:02   경광등  BUZZER", rtb: "" },
{ device: "Y440", comment: "01ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y441", comment: "01ST:   DIVERTER하강 SOL", rtb: "" },
{ device: "Y442", comment: "01ST:   DIVERTER상승 SOL", rtb: "" },
{ device: "Y443", comment: "05ST:   AIR     SUPPLY  후진 SOL", rtb: "" },
{ device: "Y444", comment: "02ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y445", comment: "06ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y446", comment: "06ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y447", comment: "05ST:   AIR     SUPPLY  전진 SOL", rtb: "" },
{ device: "Y448", comment: "03ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y449", comment: "04ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y44A", comment: "05ST:   AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "Y44B", comment: "05ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y44C", comment: "05ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y44D", comment: "05ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y44E", comment: "MAIN    AIR ON  SOL", rtb: "" },
{ device: "Y44F", comment: "06ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y450", comment: "07ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y451", comment: "06ST:   AIR     SUPPLY  후진 SOL", rtb: "" },
{ device: "Y452", comment: "06ST:   AIR     SUPPLY  전진 SOL", rtb: "" },
{ device: "Y453", comment: "06ST:   AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "Y454", comment: "08ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y455", comment: "09ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y456", comment: "09ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y457", comment: "10ST:   AIR     SUPPLY  전진 SOL", rtb: "" },
{ device: "Y458", comment: "06ST:   AIR     UNCLAMP 후진 SOL", rtb: "" },
{ device: "Y459", comment: "06ST:   AIR     UNCLAMP 전진 SOL", rtb: "" },
{ device: "Y45A", comment: "06ST:   AIR     UNCLAMP ON SOL", rtb: "" },
{ device: "Y45B", comment: "10ST:   AIR     SUPPLY  후진 SOL", rtb: "" },
{ device: "Y45C", comment: "01ST:   투입 STP하강 SOL", rtb: "" },
{ device: "Y45D", comment: "01ST:   투입 STP상승 SOL", rtb: "" },
{ device: "Y45E", comment: "01ST:   도착 STP하강 SOL", rtb: "" },
{ device: "Y45F", comment: "01ST:   도착 STP상승 SOL", rtb: "" },
{ device: "Y4C0", comment: "10ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4C1", comment: "11ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y4C2", comment: "11ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y4C3", comment: "09ST:   STOPPER 하강 sol", rtb: "" },
{ device: "Y4C4", comment: "26ST:   TILT하강", rtb: "" },
{ device: "Y4C5", comment: "26ST:   TILT상승", rtb: "" },
{ device: "Y4C6", comment: "11ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4C7", comment: "12ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4C8", comment: "13ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4C9", comment: "14ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4CA", comment: "15ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4CB", comment: "15ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y4CC", comment: "15ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y4CD", comment: "25ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4CE", comment: "16ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4CF", comment: "17ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4D0", comment: "18ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4D1", comment: "19ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4D2", comment: "20ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4D3", comment: "20ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y4D4", comment: "22ST:AIRSUPPLY  언클램프SOL", rtb: "" },
{ device: "Y4D6", comment: "21ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4D7", comment: "22ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4D8", comment: "22ST:AIRSUPPLY  후진 SOL", rtb: "" },
{ device: "Y4D9", comment: "22ST:AIRSUPPLY  전진 SOL", rtb: "" },
{ device: "Y4DA", comment: "22ST:   TILT    하강 SOL", rtb: "" },
{ device: "Y4DB", comment: "22ST:AIRSUPPLY  클램프  SOL", rtb: "" },
{ device: "Y4DC", comment: "26ST:   LIFTER  하강", rtb: "" },
{ device: "Y4DD", comment: "23ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4DE", comment: "24ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y4DF", comment: "26ST:   LIFTER  상승", rtb: "" },
{ device: "Y4F0", comment: "07ST:   AIR     SUPPLY  후진 SOL", rtb: "" },
{ device: "Y4F1", comment: "07ST:   AIR     SUPPLY  전진 SOL", rtb: "" },
{ device: "Y4F2", comment: "07ST:   AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "Y4F3", comment: "07ST:   AIR     UNCLAMP 후진 SOL", rtb: "" },
{ device: "Y4F4", comment: "07ST:   AIR     UNCLAMP 전진 SOL", rtb: "" },
{ device: "Y4F5", comment: "07ST:   AIR     UNCLAMP ON", rtb: "" },
{ device: "Y4F6", comment: "07ST:   작업완료SQ", rtb: "" },
{ device: "Y4F7", comment: "07ST:   지그    언클램프램프", rtb: "" },
{ device: "Y4F8", comment: "07ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y4F9", comment: "MAINC/V ->백로봇안전센서감지X28", rtb: "" },
{ device: "Y4FA", comment: "MAINC/V ->백로봇 안전센서감지X29", rtb: "" },
{ device: "Y4FB", comment: "18ST:   LIFTER  상승", rtb: "" },
{ device: "Y4FC", comment: "18ST:   LIFTER  하강", rtb: "" },
{ device: "Y4FD", comment: "10ST:AIRSUPPLY  클램프  SOL", rtb: "" },
{ device: "Y4FE", comment: "10ST:AIRSUPPLY  언클램프SOL", rtb: "" },
{ device: "Y540", comment: "31ST:   T/TABLE 복귀", rtb: "" },
{ device: "Y541", comment: "31ST:   T/TABLE 회전", rtb: "" },
{ device: "Y542", comment: "31ST:   T/TABLE 하강", rtb: "" },
{ device: "Y543", comment: "31ST:   T/TABLE 상승", rtb: "" },
{ device: "Y546", comment: "26ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y547", comment: "27ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y548", comment: "28ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y549", comment: "30ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y54E", comment: "37ST:   STOPPER 하강", rtb: "" },
{ device: "Y54F", comment: "29ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y550", comment: "31ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y551", comment: "32ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y552", comment: "33ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y553", comment: "34ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y554", comment: "35ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y555", comment: "36ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y557", comment: "ST38:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y558", comment: "39ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y559", comment: "39ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y55A", comment: "39ST:   TILT하강", rtb: "" },
{ device: "Y55B", comment: "39ST:   TILT상승", rtb: "" },
{ device: "Y55C", comment: "38ST:   T/TABLE 하강", rtb: "" },
{ device: "Y55D", comment: "38ST:   T/TABLE 상승", rtb: "" },
{ device: "Y55E", comment: "38ST:   T/TABLE 복귀-우턴", rtb: "" },
{ device: "Y55F", comment: "38ST:   T/TABLE 회전-좌턴", rtb: "" },
{ device: "Y5C0", comment: "57ST:   STOPPER 하강SOL", rtb: "" },
{ device: "Y5C1", comment: "48ST:   DIVERTER하강 SOL", rtb: "" },
{ device: "Y5C2", comment: "48ST:   DIVERTER상승 SOL", rtb: "" },
{ device: "Y5C3", comment: "56ST:   TILT상승", rtb: "" },
{ device: "Y5C4", comment: "58ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5C5", comment: "58ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y5C6", comment: "58ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y5C8", comment: "59ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5C9", comment: "59ST:   T/TABLE 하강", rtb: "" },
{ device: "Y5CA", comment: "59ST:   T/TABLE 상승", rtb: "" },
{ device: "Y5CB", comment: "59ST:   TILT하강", rtb: "" },
{ device: "Y5CC", comment: "59ST:   TILT상승", rtb: "" },
{ device: "Y5CD", comment: "60ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5CE", comment: "59ST:   LIFTER  하강", rtb: "" },
{ device: "Y5CF", comment: "59ST:   LIFTER  상승", rtb: "" },
{ device: "Y5D0", comment: "61ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5D1", comment: "60ST:   TILT 하강SOL", rtb: "" },
{ device: "Y5D2", comment: "60ST:   TILT 상승SOL", rtb: "" },
{ device: "Y5D3", comment: "62ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5D4", comment: "62ST:   T/TABLE 복귀 SOL", rtb: "" },
{ device: "Y5D5", comment: "62ST:   T/TABLE 회전 SOL", rtb: "" },
{ device: "Y5D6", comment: "62ST:   T/T    하강 SOL", rtb: "" },
{ device: "Y5D7", comment: "62ST:   T/T   상승 SOL", rtb: "" },
{ device: "Y5D9", comment: "63ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5DA", comment: "64ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y5DB", comment: "64ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y5DC", comment: "64ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y5DD", comment: "56ST:   TILT하강", rtb: "" },
{ device: "Y5DE", comment: "64ST:   TILT    상승 SOL", rtb: "" },
{ device: "Y5DF", comment: "65ST:   STOPPER 하강", rtb: "" },
{ device: "Y640", comment: "66ST:   STOPPER 하강", rtb: "" },
{ device: "Y641", comment: "66ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y642", comment: "66ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y643", comment: "67ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y644", comment: "67ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y646", comment: "67ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y647", comment: "68ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y648", comment: "69ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y649", comment: "69ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y64A", comment: "69ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y64B", comment: "69ST:   T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y64C", comment: "69ST:   T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y64E", comment: "70ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y650", comment: "71ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y651", comment: "71ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y652", comment: "71ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y654", comment: "72ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y655", comment: "73ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y656", comment: "73ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y657", comment: "73ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y65A", comment: "74ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y65B", comment: "75ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y65C", comment: "75ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y65D", comment: "75ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y65E", comment: "77ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y65F", comment: "76ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6B8", comment: "85ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y6B9", comment: "85ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y6C0", comment: "86ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6C1", comment: "86ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y6C2", comment: "86ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y6C3", comment: "86ST:   T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y6C4", comment: "86ST:   T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y6C5", comment: "78ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6CA", comment: "79ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6CB", comment: "79ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y6CC", comment: "79ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y6CD", comment: "79ST:   T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y6CE", comment: "79ST:   T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y6D0", comment: "80ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D1", comment: "81ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D2", comment: "82ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D3", comment: "83ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D4", comment: "84ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D6", comment: "85ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D8", comment: "85ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y6D9", comment: "87ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y6DA", comment: "87ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y6DB", comment: "87ST:   T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y6DC", comment: "87ST:   T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y740", comment: "91ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y741", comment: "91ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y745", comment: "87ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y746", comment: "88ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y747", comment: "88ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y748", comment: "88ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y749", comment: "89ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y74A", comment: "89ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y74B", comment: "89ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y74D", comment: "90ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y74E", comment: "90ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y74F", comment: "90ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y750", comment: "91ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y751", comment: "92ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y752", comment: "92ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y753", comment: "92ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y754", comment: "91ST:   AIR     SUPPLY  후진 SOL", rtb: "" },
{ device: "Y755", comment: "91ST:   AIR     SUPPLY  전진 SOL", rtb: "" },
{ device: "Y756", comment: "91ST:   AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "Y757", comment: "93ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y758", comment: "93ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y759", comment: "93ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y75A", comment: "94ST:   STOPPER 하강 SOL", rtb: "" },
{ device: "Y75B", comment: "94ST:   T/TABLE 하강 SOL", rtb: "" },
{ device: "Y75C", comment: "94ST:   T/TABLE 상승 SOL", rtb: "" },
{ device: "Y75D", comment: "94ST:   T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y75E", comment: "94ST:   T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y7C0", comment: "R_01ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7C1", comment: "R_02ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7C2", comment: "R_02ST: LIFTER  하강 SOL", rtb: "" },
{ device: "Y7C3", comment: "R_02ST: LIFTER  상승 SOL", rtb: "" },
{ device: "Y7C4", comment: "R_03ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7C5", comment: "R_03ST: LIFTER  하강 SOL", rtb: "" },
{ device: "Y7C6", comment: "R_03ST: LIFTER  상승 SOL", rtb: "" },
{ device: "Y7C7", comment: "R_05ST: AIR     UNCLAMP 후진 SOL", rtb: "" },
{ device: "Y7C8", comment: "R_05ST: AIR     UNCLAMP 전진 SOL", rtb: "" },
{ device: "Y7C9", comment: "R_04ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7CA", comment: "R_05ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7CB", comment: "R_04ST: T/TABLE 하강 SOL", rtb: "" },
{ device: "Y7CC", comment: "R_04ST: T/TABLE 상승 SOL", rtb: "" },
{ device: "Y7CD", comment: "R_04ST: T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y7CE", comment: "R_04ST: T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y7CF", comment: "R_05ST: AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "Y7D0", comment: "R_06ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7D1", comment: "R_06ST: LIFTER  하강 SOL", rtb: "" },
{ device: "Y7D2", comment: "R_06ST: LIFTER  상승 SOL", rtb: "" },
{ device: "Y7D3", comment: "R_07ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7D4", comment: "91ST:   로봇안전센서", rtb: "" },
{ device: "Y7D5", comment: "R_08ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y7D8", comment: "R_02ST: 원점완료SW LAMP", rtb: "" },
{ device: "Y7D9", comment: "R_02ST: 작업완료LAMP", rtb: "" },
{ device: "Y7DA", comment: "R_03ST: 원점완료SW LAMP", rtb: "" },
{ device: "Y7DB", comment: "R_03ST: 작업완료LAMP", rtb: "" },
{ device: "Y7DC", comment: "R_04ST: 원점복귀SW LAMP", rtb: "" },
{ device: "Y7DD", comment: "R_04ST: 작업완료LAMP", rtb: "" },
{ device: "Y7DE", comment: "R_06ST: 원점복귀SW LAMP", rtb: "" },
{ device: "Y7DF", comment: "R_06ST: 작업완료LAMP", rtb: "" },
{ device: "Y840", comment: "R_09ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y841", comment: "R_09ST: LIFTER  하강 SOL", rtb: "" },
{ device: "Y842", comment: "R_09ST: LIFTER  상승 SOL", rtb: "" },
{ device: "Y843", comment: "R_10ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y844", comment: "R_10ST: T/TABLE 하강 SOL", rtb: "" },
{ device: "Y845", comment: "R_10ST: T/TABLE 상승 SOL", rtb: "" },
{ device: "Y846", comment: "R_11ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y847", comment: "R_12ST: LIFTER  하강SOL", rtb: "" },
{ device: "Y848", comment: "R_12ST: LIFTER  상승SOL", rtb: "" },
{ device: "Y849", comment: "R_12ST: AIR     SUPPLY  후진SOL", rtb: "" },
{ device: "Y84A", comment: "R_12ST: AIR     SUPPLY  전진SOL", rtb: "" },
{ device: "Y84B", comment: "R_11ST: AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "Y84C", comment: "R_13ST: 작업완료LAMP", rtb: "" },
{ device: "Y84D", comment: "R_11ST: AIR     SUPPLY  후진 SOL", rtb: "" },
{ device: "Y84E", comment: "R_11ST: AIR     SUPPLY  전진 SOL", rtb: "" },
{ device: "Y84F", comment: "R_08ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y850", comment: "R_12ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y851", comment: "R_11ST: AIR     UNCLAMP 후진 SOL", rtb: "" },
{ device: "Y852", comment: "R_11ST: AIR     UNCLAMP 전진 SOL", rtb: "" },
{ device: "Y853", comment: "R_13ST: STOPPER 하강 SOL", rtb: "" },
{ device: "Y854", comment: "R_13ST: T/TABLE 하강 SOL", rtb: "" },
{ device: "Y855", comment: "R_13ST: T/TABLE 상승 SOL", rtb: "" },
{ device: "Y856", comment: "R_13ST: T/TABLE 복귀단  SOL", rtb: "" },
{ device: "Y857", comment: "R_13ST: T/TABLE 회전단  SOL", rtb: "" },
{ device: "Y858", comment: "R_09ST: 원점복귀SW LAMP", rtb: "" },
{ device: "Y859", comment: "R_11ST: AIR     UNCLAMP SOL", rtb: "" },
{ device: "Y85A", comment: "R_11ST: T/TABLE 상승 SOL", rtb: "" },
{ device: "Y85B", comment: "R_11ST: T/TABLE 하강 SOL", rtb: "" },
{ device: "Y85C", comment: "R_11ST: 원점복귀SW LAMP", rtb: "" },
{ device: "Y85D", comment: "R_11ST: 작업완료LAMP", rtb: "" },
{ device: "Y85E", comment: "Main    자동운전SW Lamp", rtb: "" },
{ device: "Y85F", comment: "Main    자동전지SW Lamp", rtb: "" },
{ device: "Y8A0", comment: "LH Unit 전진", rtb: "" },
{ device: "Y8A1", comment: "LH Unit 후진", rtb: "" },
{ device: "Y8A2", comment: "LH Unit 좌/우   전진", rtb: "" },
{ device: "Y8A3", comment: "LH Unit 좌/우   후진", rtb: "" },
{ device: "Y8A4", comment: "LH Unit 상승", rtb: "" },
{ device: "Y8A5", comment: "LH Unit 하강", rtb: "" },
{ device: "Y8A8", comment: "60ST:   폴딩장비레버전진SOL", rtb: "" },
{ device: "Y8A9", comment: "60ST:   폴딩장비레버후진SOL", rtb: "" },
{ device: "Y8AA", comment: "60ST:   폴딩장비레버    좌측SOL", rtb: "" },
{ device: "Y8AB", comment: "60ST:   폴딩장비레버    우측SOL", rtb: "" },
{ device: "Y8AC", comment: "60ST:   폴딩장비레버    상승SOL", rtb: "" },
{ device: "Y8AD", comment: "60ST:   폴딩장비레버    하강SOL", rtb: "" },
{ device: "Y8B0", comment: "60ST:   폴딩장비푸셔    좌측SOL", rtb: "" },
{ device: "Y8B1", comment: "60ST:   폴딩장비푸셔    우측SOL", rtb: "" },
{ device: "Y8B2", comment: "60ST:   폴딩장비푸셔    전진SOL", rtb: "" },
{ device: "Y8B3", comment: "60ST:   폴딩장비푸셔    후진SOL", rtb: "" },
{ device: "Y8BC", comment: "60ST:   폴딩장비작업완료Lamp", rtb: "" },
{ device: "Y8BF", comment: "60ST:   폴딩장비원점SQ", rtb: "" },
{ device: "Y8C0", comment: "LH Unit 전진", rtb: "" },
{ device: "Y8C1", comment: "LH Unit 후진", rtb: "" },
{ device: "Y8C2", comment: "LH Unit 좌/우   전진", rtb: "" },
{ device: "Y8C3", comment: "LH Unit 좌/우   후진", rtb: "" },
{ device: "Y8C4", comment: "LH Unit 상승", rtb: "" },
{ device: "Y8C5", comment: "LH Unit 하강", rtb: "" },
{ device: "Y8C8", comment: "68ST:   폴딩장비레버    전진SOL", rtb: "" },
{ device: "Y8C9", comment: "68ST:   폴딩장비레버    후진SOL", rtb: "" },
{ device: "Y8CA", comment: "68ST:폴딩장비레버우측작업이동SOL", rtb: "" },
{ device: "Y8CB", comment: "68ST:폴딩장비레버좌측원점이동SOL", rtb: "" },
{ device: "Y8CC", comment: "68ST:   폴딩장비레버    상승SOL", rtb: "" },
{ device: "Y8CD", comment: "68ST:   폴딩장비레버    하강SOL", rtb: "" },
{ device: "Y8D0", comment: "68ST:   폴딩장비푸셔좌측이동SOL", rtb: "" },
{ device: "Y8D1", comment: "68ST:   폴딩장비푸셔우측이동SOL", rtb: "" },
{ device: "Y8D2", comment: "68ST:   폴딩장비푸셔    전진SOL", rtb: "" },
{ device: "Y8D3", comment: "68ST:   폴딩장비푸셔    후진SOL", rtb: "" },
{ device: "Y8DC", comment: "68ST:   TOTAL   작업완료Lamp", rtb: "" },
{ device: "Y8DF", comment: "68ST:   폴딩장비원점SQ", rtb: "" },
{ device: "Y910", comment: "01ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y911", comment: "01ST:   작업완료LAMP", rtb: "" },
{ device: "Y912", comment: "02ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y913", comment: "02ST:   작업완료LAMP", rtb: "" },
{ device: "Y914", comment: "05ST:   원점완료SW LMAP", rtb: "" },
{ device: "Y915", comment: "05ST:   작업완료LAMP", rtb: "" },
{ device: "Y916", comment: "06ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y917", comment: "06ST:   작업완료LAMP", rtb: "" },
{ device: "Y918", comment: "09ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y919", comment: "09ST:   작업완료LAMP", rtb: "" },
{ device: "Y91A", comment: "3공정   트리거  완료 신호", rtb: "" },
{ device: "Y91B", comment: "09ST:   작업완료LAMP", rtb: "" },
{ device: "Y91C", comment: "01ST:   PALLET  투입배출SW LAMP", rtb: "" },
{ device: "Y91D", comment: "01ST:   투입배출완료 SW LAMP", rtb: "" },
{ device: "Y91E", comment: "6ST:    언락킹  1CYCLE  LMAP", rtb: "" },
{ device: "Y91F", comment: "6ST:    락킹    1CYCLE  LMAP", rtb: "" },
{ device: "Y930", comment: "11ST:   원점완료SW LMAP", rtb: "" },
{ device: "Y931", comment: "11ST:   작업완료LAMP", rtb: "" },
{ device: "Y932", comment: "18ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y933", comment: "18ST:   작업완료LAMP", rtb: "" },
{ device: "Y934", comment: "20ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y935", comment: "20ST:   작업완료LAMP", rtb: "" },
{ device: "Y936", comment: "26ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y937", comment: "26ST:   작업완료LAMP", rtb: "" },
{ device: "Y938", comment: "C/V ->  B/S 로봇제품있음(X32)", rtb: "" },
{ device: "Y939", comment: "C/V ->  B/S 로봇작업허가(X33)", rtb: "" },
{ device: "Y93A", comment: "C/V ->  B/S 로봇LH 사양 (X31)", rtb: "" },
{ device: "Y93B", comment: "C/V ->  B/S 로봇RH 사양 (X30)", rtb: "" },
{ device: "Y93C", comment: "MAIN    ->BACK  자동시작X7C", rtb: "" },
{ device: "Y93D", comment: "MAIN    ->BACK  자동정지X7D", rtb: "" },
{ device: "Y93E", comment: "15ST -> Back C/V제품없음/X7E", rtb: "" },
{ device: "Y944", comment: "31ST:   원점완료S/W LAMP", rtb: "" },
{ device: "Y945", comment: "31ST:   작업완료LAMP", rtb: "" },
{ device: "Y950", comment: "31ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y951", comment: "31ST:   작업완료LAMP", rtb: "" },
{ device: "Y952", comment: "38ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y953", comment: "38ST:   작업완료LAMP", rtb: "" },
{ device: "Y954", comment: "39ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y955", comment: "39ST:   작업완료LAMP", rtb: "" },
{ device: "Y956", comment: "47ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y957", comment: "47ST:   작업완료LAMP", rtb: "" },
{ device: "Y958", comment: "31ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y959", comment: "38ST:   1 CYCLE  SW LAMP", rtb: "" },
{ device: "Y95A", comment: "47ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y95C", comment: "25ST:   T/TABLE 우회전  SOL", rtb: "" },
{ device: "Y95D", comment: "25ST:   T/TABLE 우복귀  SOL", rtb: "" },
{ device: "Y970", comment: "48ST:   원점완료SW LMAP", rtb: "" },
{ device: "Y971", comment: "48ST:   작업완료LAMP", rtb: "" },
{ device: "Y972", comment: "58ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y973", comment: "58ST:   작업완료LAMP", rtb: "" },
{ device: "Y974", comment: "59ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y975", comment: "59ST:   TOTAL   작업완료램프", rtb: "" },
{ device: "Y976", comment: "60ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y977", comment: "60ST:   작업완료LAMP", rtb: "" },
{ device: "Y978", comment: "62ST:   원점완료SW LMAP", rtb: "" },
{ device: "Y979", comment: "62ST:   작업완료LAMP", rtb: "" },
{ device: "Y97A", comment: "64ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y97B", comment: "64ST:   작업완료LAMP", rtb: "" },
{ device: "Y97C", comment: "59ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y97D", comment: "56ST:   TOTAL   작업완료램프", rtb: "" },
{ device: "Y97E", comment: "67ST:   LIFTER  상승 SOL", rtb: "" },
{ device: "Y97F", comment: "67ST:   LIFTER  하강 SOL", rtb: "" },
{ device: "Y990", comment: "66ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y991", comment: "66ST:   작업완료LAMP", rtb: "" },
{ device: "Y992", comment: "62ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y993", comment: "62ST:   작업완료LAMP", rtb: "" },
{ device: "Y994", comment: "71ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y995", comment: "71ST:   작업완료LAMP", rtb: "" },
{ device: "Y996", comment: "65ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y997", comment: "65ST:   작업완료LAMP", rtb: "" },
{ device: "Y998", comment: "75ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y999", comment: "75ST:   작업완료LAMP", rtb: "" },
{ device: "Y99A", comment: "62ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y99E", comment: "C/V ->  73ST로봇PASS SW ??", rtb: "" },
{ device: "Y99F", comment: "C/V ->  75ST로봇PASS SW", rtb: "" },
{ device: "Y9B0", comment: "로보트  안전센서스팀로봇X3A", rtb: "" },
{ device: "Y9B4", comment: "79ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y9B5", comment: "79ST:   작업완료LAMP", rtb: "" },
{ device: "Y9B6", comment: "87ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y9B7", comment: "87ST:   작업완료LAMP", rtb: "" },
{ device: "Y9B8", comment: "C/V->   69ST히팅제품있음", rtb: "" },
{ device: "Y9B9", comment: "78ST:   PALLET  도착", rtb: "" },
{ device: "Y9BA", comment: "78ST:   MAIN    자동운전", rtb: "" },
{ device: "Y9BB", comment: "87ST:   OK 버튼 LAMP", rtb: "" },
{ device: "Y9BC", comment: "87ST:   NG 버튼 LAMP", rtb: "" },
{ device: "Y9BE", comment: "87ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y9BF", comment: "79ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y9C4", comment: "89ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9C5", comment: "89ST:   작업완료LAMP", rtb: "" },
{ device: "Y9C8", comment: "92ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9C9", comment: "92ST:   작업완료LAMP", rtb: "" },
{ device: "Y9CA", comment: "93ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9CB", comment: "93ST:   작업완료LAMP", rtb: "" },
{ device: "Y9CC", comment: "94ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9CD", comment: "94ST:   작업완료LAMP", rtb: "" },
{ device: "Y9D0", comment: "86ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9D1", comment: "86ST:   작업완료LAMP", rtb: "" },
{ device: "Y9D2", comment: "88ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y9D3", comment: "88ST:   작업완료LAMP", rtb: "" },
{ device: "Y9D4", comment: "89ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9D5", comment: "89ST:   작업완료LAMP", rtb: "" },
{ device: "Y9D6", comment: "90ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9D7", comment: "90ST:   작업완료LAMP", rtb: "" },
{ device: "Y9D8", comment: "92ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9D9", comment: "92ST:   작업완료LAMP", rtb: "" },
{ device: "Y9DB", comment: "91ST:   PALLET  UNCLAMP 완료램프", rtb: "" },
{ device: "Y9DC", comment: "94ST:   원점완료SW LAMP", rtb: "" },
{ device: "Y9DD", comment: "94ST:   작업완료LAMP", rtb: "" },
{ device: "Y9DE", comment: "91ST:   원점복귀SW LAMP", rtb: "" },
{ device: "Y9DF", comment: "91ST:   작업완료LAMP", rtb: "" },
{ device: "Y9F0", comment: "6ST:    TOWER   LAMP -R", rtb: "" },
{ device: "Y9F1", comment: "6ST:    TOWER   LAMP -B", rtb: "" },
{ device: "Y9F2", comment: "서열정보트리거", rtb: "" },
{ device: "Y9F4", comment: "C/V ->  ST#05로봇LH 사양", rtb: "" },
{ device: "Y9F5", comment: "C/V ->  트랙로봇안착완료신호", rtb: "" },
{ device: "Y9F6", comment: "C/V    -트랙로봇작업    허가", rtb: "" },
{ device: "Y9F7", comment: "C/V ->  상차로봇RH 사양", rtb: "" },
{ device: "Y9F8", comment: "히팅부스인터락  RELAY", rtb: "" },
{ device: "Y9FA", comment: "2열 NG  TOWER   LAMP", rtb: "" },
{ device: "Y9FB", comment: "2열 OK  TOWER   LAMP", rtb: "" },
{ device: "Y9FC", comment: "2열 OK  BUZZER", rtb: "" },
{ device: "Y9FD", comment: "2열 NG  BUZZER", rtb: "" },
{ device: "Y9FE", comment: "C/V ->  트랙로봇안전센서X22", rtb: "" },
{ device: "Y0A50", comment: "C/V->스팀로봇안전이상    X55C", rtb: "" },
{ device: "Y0A51", comment: "60ST:   비상정지램프", rtb: "" },
{ device: "Y0A52", comment: "61ST: LIFTER  하강", rtb: "" },
{ device: "Y0A53", comment: "61ST: LIFTER  상승", rtb: "" },
{ device: "Y0A54", comment: "C/V ->  60ST:   작업허가", rtb: "" },
{ device: "Y0A55", comment: "C/V ->  60ST검사틸팅상태", rtb: "" },
{ device: "Y0A56", comment: "C/V->   60ST검사PASS 상태", rtb: "" },
{ device: "Y0A58", comment: "C/V->   62ST검사자동", rtb: "" },
{ device: "Y0A59", comment: "C/V ->  62ST검사작업허가", rtb: "" },
{ device: "Y0A5A", comment: "C/V->   62ST검사PASS 상태", rtb: "" },
{ device: "Y0A5C", comment: "C/V ->  64ST검사제품있음", rtb: "" },
{ device: "Y0A5D", comment: "C/V ->  64ST검사작업허가", rtb: "" },
{ device: "Y0A5E", comment: "C/V->   64ST검사PASS 상태", rtb: "" },
{ device: "Y0A70", comment: "C/V ->  66ST검사제품있음", rtb: "" },
{ device: "Y0A71", comment: "C/V ->  66ST검사작업허가", rtb: "" },
{ device: "Y0A72", comment: "66ST:   검사    PASS", rtb: "" },
{ device: "Y0A74", comment: "C/V ->  53ST검사LH 검사", rtb: "" },
{ device: "Y0A75", comment: "C/V->   53ST검사PASS", rtb: "" },
{ device: "Y0A76", comment: "C/V->   53ST검사LH 검사", rtb: "" },
{ device: "Y0A77", comment: "C/V->   53ST검사RH 사양", rtb: "" },
{ device: "Y0A78", comment: "C/V->   65ST로보PALLET  감지", rtb: "" },
{ device: "Y0A79", comment: "C/V ->  65ST로봇작업허가", rtb: "" },
{ device: "Y0A7A", comment: "C/V ->  65ST로봇LH 제품 감지", rtb: "" },
{ device: "Y0A7B", comment: "C/V ->  65ST로봇RH 제품 감지", rtb: "" },
{ device: "Y0A7C", comment: "C/V ->  67ST로봇제품감지", rtb: "" },
{ device: "Y0A7D", comment: "C/V ->  67ST로봇작업허가", rtb: "" },
{ device: "Y0A7E", comment: "C/V ->  67ST로봇LH 감지", rtb: "" },
{ device: "Y0A7F", comment: "C/V ->  67ST로봇RH 감지", rtb: "" },
{ device: "Y0AB0", comment: "C/V ->  89ST트랙제품있음", rtb: "" },
{ device: "Y0AB1", comment: "C/V ->  72ST트랙작업허가", rtb: "" },
{ device: "Y0AB2", comment: "C/V ->  89ST트랙작업허가", rtb: "" },
{ device: "Y0AB3", comment: "C/V ->  89ST유격원점요구신호", rtb: "" },
{ device: "Y0AB4", comment: "92ST:   PALLET  L/R     Reset", rtb: "" },
{ device: "Y0AB5", comment: "92ST:   PALLET  들뜸감지", rtb: "" },
{ device: "Y0AB6", comment: "외관촬영 SP(-->X38)", rtb: "" },
{ device: "Y0AB7", comment: "외관촬영 SP(-->X39)", rtb: "" },
{ device: "Y0AB8", comment: "92ST:   로봇    지그도착", rtb: "" },
{ device: "Y0AB9", comment: "92ST:   로봇작업허가", rtb: "" },
{ device: "Y0ABA", comment: "92ST:   로봇    LH감지", rtb: "" },
{ device: "Y0ABB", comment: "92ST:   로봇    RH감지", rtb: "" },
{ device: "Y0ABC", comment: "외관촬영 SP(-->X3A)", rtb: "" },
{ device: "Y0ABD", comment: "89ST:   NG 버튼 LAMP", rtb: "" },
{ device: "Y0ABE", comment: "94ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y0ABF", comment: "86ST:   1 CYCLE SW LAMP", rtb: "" },
{ device: "Y0AF2", comment: "R_10ST: 원점복귀SW LAMP", rtb: "" },
{ device: "Y0AF3", comment: "R_10ST: 작업완료LAMP", rtb: "" },
{ device: "Y0AF7", comment: "R_13ST: 배출요구SW LAMP", rtb: "" },
{ device: "Y0AF8", comment: "R_13ST: 원점복귀SW LAMP", rtb: "" },
{ device: "Y0AF9", comment: "R_13ST: 작업완료LAMP", rtb: "" },
{ device: "Y0AFA", comment: "C/V->   검사기  제품도착", rtb: "" },
{ device: "Y0AFB", comment: "C/V->   검사기  작업허가", rtb: "" },
{ device: "Y0AFC", comment: "C/V->   검사기  PASS모드", rtb: "" },
{ device: "Y0AFD", comment: "??", rtb: "" },
{ device: "Y1020", comment: "MAIN    C/V_01  A인버터 기동", rtb: "" },
{ device: "Y1021", comment: "CV_01   A인버터 RESET", rtb: "" },
{ device: "Y1022", comment: "MAIN    C/V_01  모터 'B'기동출력", rtb: "" },
{ device: "Y1023", comment: "CV_01   B인버터 RESET", rtb: "" },
{ device: "Y1024", comment: "MAIN    C/V_02  A인버터 기동", rtb: "" },
{ device: "Y1025", comment: "CV_02   A인버터 RESET", rtb: "" },
{ device: "Y1026", comment: "MAIN    C/V_02  모터 'B'기동출력", rtb: "" },
{ device: "Y1027", comment: "CV_02   B인버터 RESET", rtb: "" },
{ device: "Y1028", comment: "MAIN    C/V_05  A인버터 기동", rtb: "" },
{ device: "Y1029", comment: "CV_05   A인버터 RESET", rtb: "" },
{ device: "Y102A", comment: "MAIN    C/V_05  B인버터 기동", rtb: "" },
{ device: "Y102B", comment: "CV_05   B인버터 RESET", rtb: "" },
{ device: "Y102C", comment: "MAIN    C/V_06  A인버터 기동", rtb: "" },
{ device: "Y102D", comment: "CV_06   A인버터 RESET", rtb: "" },
{ device: "Y102E", comment: "MAIN    C/V_06  B인버터 기동", rtb: "" },
{ device: "Y102F", comment: "CV_06   B인버터 RESET", rtb: "" },
{ device: "Y1030", comment: "MAIN    C/V_01  'A'     MC기동", rtb: "" },
{ device: "Y1031", comment: "MAIN    C/V_01  'B'     MC기동", rtb: "" },
{ device: "Y1032", comment: "MAIN    C/V_02  'A'     MC기동", rtb: "" },
{ device: "Y1033", comment: "MAIN    C/V_02  'B'     MC기동", rtb: "" },
{ device: "Y1034", comment: "MAIN    C/V_05  'A'     MC기동", rtb: "" },
{ device: "Y1035", comment: "MAIN    C/V_05  'B'     MC기동", rtb: "" },
{ device: "Y1036", comment: "MAIN    C/V_06  'A'     MC기동", rtb: "" },
{ device: "Y1037", comment: "MAIN    C/V_06  'B'     MC기동", rtb: "" },
{ device: "Y1038", comment: "MAIN    C/V_01  INV 'A' M1 선택", rtb: "" },
{ device: "Y1039", comment: "MAIN    C/V_01  INV 'A' M2 선택", rtb: "" },
{ device: "Y103A", comment: "MAIN    C/V_01  INV 'B' M1 선택", rtb: "" },
{ device: "Y103B", comment: "MAIN    C/V_01  INV 'B' M2 선택", rtb: "" },
{ device: "Y1051", comment: "C/V->   40ST    작업허가", rtb: "" },
{ device: "Y1071", comment: "C/V ->  48ST검사작업허가", rtb: "" },
{ device: "Y107A", comment: "C/V ->  55ST로봇RH 제품 감지", rtb: "" },
{ device: "Y10B0", comment: "72ST트랙-> C/V  RH 제품 작업허가", rtb: "" },
{ device: "Y10B1", comment: "72ST트랙-> C/V  LH 제품 작업허가", rtb: "" },
{ device: "Y10B4", comment: "C/V ->  75ST로봇LH 감지", rtb: "" },
{ device: "Y10B5", comment: "C/V->   75ST로봇RH 감지", rtb: "" },
{ device: "Y10B6", comment: "C/V->   75ST로봇작업허가", rtb: "" },
{ device: "Y1121", comment: "38ST:   STOPPER 하강", rtb: "" },
{ device: "Y1122", comment: "39ST:   STOPPER 하강", rtb: "" },
{ device: "Y1123", comment: "40ST:   STOPPER 하강", rtb: "" },
{ device: "Y1124", comment: "41ST:   STOPPER 하강", rtb: "" },
{ device: "Y1125", comment: "42ST:   STOPPER 하강", rtb: "" },
{ device: "Y1126", comment: "43ST:   STOPPER 하강", rtb: "" },
{ device: "Y1127", comment: "44ST:   STOPPER 하강", rtb: "" },
{ device: "Y1128", comment: "45ST:   STOPPER 하강", rtb: "" },
{ device: "Y1129", comment: "46ST:   LIFTER  하강", rtb: "" },
{ device: "Y112A", comment: "46ST:   LIFTER  상승", rtb: "" },
{ device: "Y112B", comment: "47ST:   STOPPER 하강", rtb: "" },
{ device: "Y112C", comment: "47ST:   T/TABLE 하강", rtb: "" },
{ device: "Y112D", comment: "47ST:   T/TABLE 상승", rtb: "" },
{ device: "Y112E", comment: "47ST:   T/TABLE 회전", rtb: "" },
{ device: "Y112F", comment: "47ST:   T/TABLE 복귀", rtb: "" },
{ device: "Y1130", comment: "40ST:   비상정지램프", rtb: "" },
{ device: "Y1132", comment: "47ST:   1 CYCLE 램프", rtb: "" },
{ device: "Y1133", comment: "47ST:   원점복귀램프", rtb: "" },
{ device: "Y1138", comment: "46ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E0", comment: "48ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E1", comment: "48ST:   DIVERTER하강", rtb: "" },
{ device: "Y11E2", comment: "48ST:   DIVERTER상승", rtb: "" },
{ device: "Y11E3", comment: "49ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E4", comment: "50ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E5", comment: "51ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E6", comment: "52ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E7", comment: "53ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E8", comment: "54ST:   STOPPER 하강", rtb: "" },
{ device: "Y11E9", comment: "54ST:   LIFTER  하강", rtb: "" },
{ device: "Y11EA", comment: "54ST:   LIFTER  상승", rtb: "" },
{ device: "Y11EB", comment: "55ST:   STOPPER 하강", rtb: "" },
{ device: "Y11EC", comment: "56ST:   STOPPER 하강", rtb: "" },
{ device: "Y11ED", comment: "53ST:   TOTAL   작업완료램프", rtb: "" },
{ device: "Y11F2", comment: "54ST:   전극    후진", rtb: "" },
{ device: "Y11F3", comment: "54ST:   전극    전진", rtb: "" },
{ device: "Y11F4", comment: "56ST:   LIFTER  하강", rtb: "" },
{ device: "Y11F5", comment: "56ST:   LIFTER  상승", rtb: "" },
{ device: "Y11FA", comment: "54ST:   원점복귀램프", rtb: "" },
{ device: "Y11FB", comment: "54ST:   TOTAL   작업완료램프", rtb: "" },
{ device: "Y11FC", comment: "52ST:   원점복귀램프", rtb: "" },
{ device: "Y11FD", comment: "52ST:   TOTAL   작업완료램프", rtb: "" },
{ device: "Y1200", comment: "52ST:   BARCODE 지그도착", rtb: "" },
{ device: "Y1201", comment: "52ST:   BARCODE 검사요청", rtb: "" },
{ device: "Y1202", comment: "52ST:   BARCODE SPARE", rtb: "" },
{ device: "Y1203", comment: "52ST:   BARCODE SPARE", rtb: "" },
{ device: "Y1204", comment: "54ST:   IMS검사 지그도착", rtb: "" },
{ device: "Y1205", comment: "54ST:   IMS검사 검사요청", rtb: "" },
{ device: "Y1206", comment: "54ST:   IMS검사 PASS", rtb: "" },
{ device: "Y1207", comment: "54ST:   IMS검사 원점", rtb: "" },
{ device: "Y1208", comment: "53ST:   LIFTER  하강", rtb: "" },
{ device: "Y1209", comment: "53ST:   LIFTER  상승", rtb: "" },
{ device: "Y120C", comment: "50ST:   컨베어->검사기  지그도착", rtb: "" },
{ device: "Y120D", comment: "50ST:   컨베어->검사기  PASS", rtb: "" },
{ device: "Y120E", comment: "50ST:   컨베어->검사기  배출중", rtb: "" },
{ device: "Y120F", comment: "50ST:   컨베어->검사기  SPARE", rtb: "" },
{ device: "Y121A", comment: "55ST    통풍검  뮤팅신호", rtb: "" },
{ device: "Y121B", comment: "55ST    통풍검사 뮤팅신호", rtb: "" },
{ device: "Y1240", comment: "53ST:   원점복귀완료램프", rtb: "" },
{ device: "Y1241", comment: "53ST:   TOTAL   작업완료", rtb: "" },
{ device: "Y1242", comment: "53ST:   전극    전진", rtb: "" },
{ device: "Y1243", comment: "53ST:   전극    후진", rtb: "" },
{ device: "Y1246", comment: "49ST:AIRSUPPLY  전진    SOL", rtb: "" },
{ device: "Y1247", comment: "49ST:AIRSUPPLY  후진    SOL", rtb: "" },
{ device: "Y1248", comment: "49ST:AIRSUPPLY  클램프  SOL", rtb: "" },
{ device: "Y1249", comment: "49ST:AIRSUPPLY  언클램프SOL", rtb: "" },
{ device: "Y1250", comment: "61ST: 검사기 제품도착(INT:X0E)", rtb: "" },
{ device: "Y1251", comment: "61ST: 검사기 검사허가(INT:X0F)", rtb: "" },
{ device: "Y1252", comment: "61ST: 검사기 작업패스(INT:X1E)", rtb: "" },
{ device: "Y1253", comment: "61ST: SPARE(INT:X1F)", rtb: "" },
{ device: "Y1256", comment: "61ST: 작업완료램프", rtb: "" },
{ device: "Y1258", comment: "56ST->  통풍    제품도착", rtb: "" },
{ device: "Y1259", comment: "56ST->  통풍    검사허가", rtb: "" },
{ device: "Y125A", comment: "56ST->  통풍    PASS", rtb: "" },
{ device: "Y125B", comment: "56ST->  통풍    SPARE", rtb: "" },
];