const devicesl = [
{ device: "L1001", comment: "01ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1005", comment: "01ST:   작업완료", rtb: "" },
{ device: "L1006", comment: "01ST:   AIR     작업완료", rtb: "" },
{ device: "L1051", comment: "02ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1055", comment: "02ST:   작업완료", rtb: "" },
{ device: "L1056", comment: "02ST:   AIR     작업완료", rtb: "" },
{ device: "L1101", comment: "03ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1105", comment: "03ST:   작업완료", rtb: "" },
{ device: "L1106", comment: "03ST:   AIR     작업완료", rtb: "" },
{ device: "L1109", comment: "03ST:   MES     작업완료", rtb: "" },
{ device: "L1151", comment: "04ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1155", comment: "04ST:   작업완료", rtb: "" },
{ device: "L1156", comment: "04ST:   AIR     작업완료", rtb: "" },
{ device: "L1201", comment: "05ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1204", comment: "05ST:   AIR 공급작업완료", rtb: "" },
{ device: "L1205", comment: "05ST:   작업완료", rtb: "" },
{ device: "L1206", comment: "05ST:   AIR     작업완료", rtb: "" },
{ device: "L1251", comment: "06ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1255", comment: "06ST:   작업완료", rtb: "" },
{ device: "L1256", comment: "06ST:   AIR     작업완료", rtb: "" },
{ device: "L1301", comment: "07ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1304", comment: "07ST:   인타운  작업완료", rtb: "" },
{ device: "L1306", comment: "07ST:   AIR     작업완료", rtb: "" },
{ device: "L1351", comment: "08ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1355", comment: "08ST:   작업완료", rtb: "" },
{ device: "L1356", comment: "08ST:   AIR     작업완료", rtb: "" },
{ device: "L1401", comment: "09ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1405", comment: "09ST:   작업완료", rtb: "" },
{ device: "L1406", comment: "09ST:   AIR     작업완료", rtb: "" },
{ device: "L1451", comment: "10ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1455", comment: "10ST:   작업완료", rtb: "" },
{ device: "L1456", comment: "10ST:   AIR     작업완료", rtb: "" },
{ device: "L1501", comment: "11ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1505", comment: "11ST:   작업완료", rtb: "" },
{ device: "L1506", comment: "11ST:   AIR     작업완료", rtb: "" },
{ device: "L1551", comment: "12ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1555", comment: "12ST:   작업완료", rtb: "" },
{ device: "L1556", comment: "12ST:   AIR     작업완료", rtb: "" },
{ device: "L1601", comment: "13ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1605", comment: "13ST:   작업완료", rtb: "" },
{ device: "L1606", comment: "13ST:   AIR     작업완료", rtb: "" },
{ device: "L1651", comment: "14ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1655", comment: "14ST:   작업완료", rtb: "" },
{ device: "L1656", comment: "14ST:   AIR     작업완료", rtb: "" },
{ device: "L1701", comment: "15ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1705", comment: "15ST:   작업완료", rtb: "" },
{ device: "L1706", comment: "15ST:   AIR     작업완료", rtb: "" },
{ device: "L1751", comment: "16ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1755", comment: "16ST:   작업완료", rtb: "" },
{ device: "L1756", comment: "16ST:   AIR     작업완료", rtb: "" },
{ device: "L1801", comment: "17ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1805", comment: "17ST:   작업완료", rtb: "" },
{ device: "L1806", comment: "17ST:   AIR     작업완료", rtb: "" },
{ device: "L1851", comment: "18ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1855", comment: "18ST:   작업완료", rtb: "" },
{ device: "L1856", comment: "18ST:   AIR     작업완료", rtb: "" },
{ device: "L1901", comment: "19ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1905", comment: "19ST:   작업완료", rtb: "" },
{ device: "L1906", comment: "19ST:   AIR     작업완료", rtb: "" },
{ device: "L1951", comment: "20ST:   TOTAL   작업완료", rtb: "" },
{ device: "L1954", comment: "20ST:   인타운  작업완료", rtb: "" },
{ device: "L1955", comment: "20ST:   작업완료", rtb: "" },
{ device: "L1956", comment: "20ST:   AIR     작업완료", rtb: "" },
{ device: "L2001", comment: "21ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2005", comment: "21ST:   작업완료", rtb: "" },
{ device: "L2006", comment: "21ST:   AIR     작업완료", rtb: "" },
{ device: "L2051", comment: "22ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2054", comment: "22ST:   TILTING 작업완료", rtb: "" },
{ device: "L2055", comment: "22ST:   작업완료", rtb: "" },
{ device: "L2056", comment: "22ST:   AIR     작업완료", rtb: "" },
{ device: "L2101", comment: "23ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2105", comment: "23ST:   작업완료", rtb: "" },
{ device: "L2106", comment: "23ST:   AIR     작업완료", rtb: "" },
{ device: "L2151", comment: "24ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2155", comment: "24ST:   작업완료", rtb: "" },
{ device: "L2156", comment: "24ST:   AIR     작업완료", rtb: "" },
{ device: "L2201", comment: "25ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2205", comment: "25ST:   작업완료", rtb: "" },
{ device: "L2206", comment: "25ST:   AIR     작업완료", rtb: "" },
{ device: "L2251", comment: "26ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2254", comment: "26ST:   틸팅작업완료02", rtb: "" },
{ device: "L2255", comment: "26ST:   틸팅작업완료01", rtb: "" },
{ device: "L2256", comment: "26ST:   AIR     작업완료", rtb: "" },
{ device: "L2301", comment: "27ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2305", comment: "27ST:   작업완료", rtb: "" },
{ device: "L2306", comment: "27ST:   AIR     작업완료", rtb: "" },
{ device: "L2351", comment: "28ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2355", comment: "28ST:   작업완료", rtb: "" },
{ device: "L2356", comment: "28ST:   AIR     작업완료", rtb: "" },
{ device: "L2401", comment: "29ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2404", comment: "29ST:   TILTING 작업완료", rtb: "" },
{ device: "L2405", comment: "29ST:   작업완료", rtb: "" },
{ device: "L2406", comment: "29ST:   AIR     작업완료", rtb: "" },
{ device: "L2451", comment: "30ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2455", comment: "30ST:   작업완료", rtb: "" },
{ device: "L2456", comment: "30ST:   AIR     작업완료", rtb: "" },
{ device: "L2501", comment: "31ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2504", comment: "31ST:   TILT    작업완료", rtb: "" },
{ device: "L2505", comment: "31ST:   작업완료", rtb: "" },
{ device: "L2506", comment: "31ST:   AIR     작업완료", rtb: "" },
{ device: "L2551", comment: "32ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2555", comment: "32ST:   작업완료", rtb: "" },
{ device: "L2556", comment: "32ST:   AIR     작업완료", rtb: "" },
{ device: "L2601", comment: "33ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2605", comment: "33ST:   작업완료", rtb: "" },
{ device: "L2606", comment: "33ST:   AIR     작업완료", rtb: "" },
{ device: "L2651", comment: "34ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2655", comment: "34ST:   작업완료", rtb: "" },
{ device: "L2656", comment: "34ST:   AIR     작업완료", rtb: "" },
{ device: "L2701", comment: "35ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2705", comment: "35ST:   작업완료", rtb: "" },
{ device: "L2706", comment: "35ST:   AIR     작업완료", rtb: "" },
{ device: "L2751", comment: "36ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2755", comment: "36ST:   작업완료", rtb: "" },
{ device: "L2756", comment: "36ST:   AIR     작업완료", rtb: "" },
{ device: "L2801", comment: "46ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2805", comment: "46ST:   작업완료", rtb: "" },
{ device: "L2806", comment: "46ST:   AIR     작업완료", rtb: "" },
{ device: "L2851", comment: "47ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2855", comment: "47ST:   작업완료", rtb: "" },
{ device: "L2856", comment: "47ST:   AIR     작업완료", rtb: "" },
{ device: "L2901", comment: "48ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2905", comment: "48ST:   작업완료", rtb: "" },
{ device: "L2906", comment: "48ST:   AIR     작업완료", rtb: "" },
{ device: "L2951", comment: "58ST:   TOTAL   작업완료", rtb: "" },
{ device: "L2954", comment: "58ST:   인타운  작업완료", rtb: "" },
{ device: "L2955", comment: "58ST:   작업완료", rtb: "" },
{ device: "L2956", comment: "58ST:   AIR     작업완료", rtb: "" },
{ device: "L3001", comment: "59ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3004", comment: "59ST:   PODS    작업완료", rtb: "" },
{ device: "L3005", comment: "59ST:   작업완료", rtb: "" },
{ device: "L3006", comment: "58ST:   AIR     작업완료", rtb: "" },
{ device: "L3051", comment: "60ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3054", comment: "60ST:   TILTING 작업완료", rtb: "" },
{ device: "L3055", comment: "60ST:   폴딩장비작업완료", rtb: "" },
{ device: "L3056", comment: "60ST:   AIR     작업완료", rtb: "" },
{ device: "L3101", comment: "61ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3105", comment: "61ST:   작업완료", rtb: "" },
{ device: "L3106", comment: "61ST:   AIR     작업완료", rtb: "" },
{ device: "L3151", comment: "62ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3154", comment: "62ST:   TILTING 작업완료", rtb: "" },
{ device: "L3155", comment: "62ST:   작업완료", rtb: "" },
{ device: "L3156", comment: "62ST:   AIR     작업완료", rtb: "" },
{ device: "L3201", comment: "63ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3205", comment: "63ST:   작업완료", rtb: "" },
{ device: "L3206", comment: "63ST:   AIR     작업완료", rtb: "" },
{ device: "L3251", comment: "64ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3254", comment: "64ST:   TILTING 작업완료", rtb: "" },
{ device: "L3255", comment: "64ST:   작업완료", rtb: "" },
{ device: "L3256", comment: "64ST:   AIR     작업완료", rtb: "" },
{ device: "L3301", comment: "65ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3305", comment: "65ST:   작업완료", rtb: "" },
{ device: "L3306", comment: "65ST:   AIR     작업완료", rtb: "" },
{ device: "L3351", comment: "66ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3354", comment: "66ST:   틸팅    작업완료", rtb: "" },
{ device: "L3355", comment: "66ST:   작업완료", rtb: "" },
{ device: "L3356", comment: "66ST:   AIR     작업완료", rtb: "" },
{ device: "L3401", comment: "67ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3405", comment: "67ST:   작업완료", rtb: "" },
{ device: "L3406", comment: "67ST:   AIR     작업완료", rtb: "" },
{ device: "L3451", comment: "68ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3455", comment: "68ST:   작업완료", rtb: "" },
{ device: "L3456", comment: "68ST:   AIR     작업완료", rtb: "" },
{ device: "L3501", comment: "69ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3505", comment: "69ST:   작업완료", rtb: "" },
{ device: "L3506", comment: "69ST:   AIR     작업완료", rtb: "" },
{ device: "L3551", comment: "70ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3555", comment: "70ST:   작업완료", rtb: "" },
{ device: "L3556", comment: "70ST:   AIR     작업완료", rtb: "" },
{ device: "L3601", comment: "71ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3605", comment: "71ST:   작업완료", rtb: "" },
{ device: "L3606", comment: "71ST:   AIR     작업완료", rtb: "" },
{ device: "L3651", comment: "72ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3655", comment: "72ST:   작업완료", rtb: "" },
{ device: "L3656", comment: "72ST:   AIR     작업완료", rtb: "" },
{ device: "L3701", comment: "73ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3705", comment: "73ST:   작업완료", rtb: "" },
{ device: "L3706", comment: "73ST:   AIR     작업완료", rtb: "" },
{ device: "L3751", comment: "74ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3755", comment: "74ST:   작업완료", rtb: "" },
{ device: "L3756", comment: "74ST:   AIR     작업완료", rtb: "" },
{ device: "L3801", comment: "75ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3805", comment: "75ST:   작업완료", rtb: "" },
{ device: "L3806", comment: "75ST:   AIR     작업완료", rtb: "" },
{ device: "L3851", comment: "76ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3855", comment: "76ST:   작업완료", rtb: "" },
{ device: "L3856", comment: "76ST:   AIR     작업완료", rtb: "" },
{ device: "L3901", comment: "77ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3905", comment: "77ST:   작업완료", rtb: "" },
{ device: "L3906", comment: "77ST:   AIR     작업완료", rtb: "" },
{ device: "L3951", comment: "78ST:   TOTAL   작업완료", rtb: "" },
{ device: "L3955", comment: "78ST:   작업완료", rtb: "" },
{ device: "L3956", comment: "78ST:   AIR     작업완료", rtb: "" },
{ device: "L4001", comment: "79ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4005", comment: "79ST:   작업완료", rtb: "" },
{ device: "L4006", comment: "79ST:   AIR     작업완료", rtb: "" },
{ device: "L4051", comment: "80ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4055", comment: "80ST:   작업완료", rtb: "" },
{ device: "L4056", comment: "80ST:   AIR     작업완료", rtb: "" },
{ device: "L4101", comment: "81ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4105", comment: "81ST:   작업완료", rtb: "" },
{ device: "L4106", comment: "81ST:   AIR     작업완료", rtb: "" },
{ device: "L4151", comment: "82ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4155", comment: "82ST:   작업완료", rtb: "" },
{ device: "L4156", comment: "82ST:   AIR     작업완료", rtb: "" },
{ device: "L4201", comment: "83ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4205", comment: "83ST:   작업완료", rtb: "" },
{ device: "L4206", comment: "83ST:   AIR     작업완료", rtb: "" },
{ device: "L4251", comment: "84ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4255", comment: "84ST:   작업완료", rtb: "" },
{ device: "L4256", comment: "84ST:   AIR     작업완료", rtb: "" },
{ device: "L4301", comment: "85ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4305", comment: "85ST:   작업완료", rtb: "" },
{ device: "L4306", comment: "85ST:   AIR     작업완료", rtb: "" },
{ device: "L4351", comment: "86ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4354", comment: "86ST:   T/TABLE 작업완료", rtb: "" },
{ device: "L4355", comment: "86ST:   인타운  작업완료", rtb: "" },
{ device: "L4356", comment: "86ST:   AIR     작업완료", rtb: "" },
{ device: "L4377", comment: "86ST:   MES QC상위작업완료", rtb: "" },
{ device: "L4401", comment: "87ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4404", comment: "87ST:   T/TABLE 작업완료", rtb: "" },
{ device: "L4405", comment: "86ST,   87ST:   작업완료", rtb: "" },
{ device: "L4406", comment: "86ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4451", comment: "88ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4455", comment: "88ST:   작업완료", rtb: "" },
{ device: "L4456", comment: "88ST:   AIR     작업완료", rtb: "" },
{ device: "L4501", comment: "89ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4505", comment: "89ST:   작업완료", rtb: "" },
{ device: "L4506", comment: "89ST:   AIR     작업완료", rtb: "" },
{ device: "L4551", comment: "90ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4555", comment: "90ST:   작업완료", rtb: "" },
{ device: "L4556", comment: "90ST:   AIR     작업완료", rtb: "" },
{ device: "L4601", comment: "91ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4605", comment: "91ST:   작업완료", rtb: "" },
{ device: "L4606", comment: "91ST:   AIR     작업완료", rtb: "" },
{ device: "L4651", comment: "92ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4655", comment: "92ST:   작업완료", rtb: "" },
{ device: "L4656", comment: "92ST:   AIR     작업완료", rtb: "" },
{ device: "L4701", comment: "93ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4705", comment: "93ST:   작업완료", rtb: "" },
{ device: "L4706", comment: "93ST:   AIR     작업완료", rtb: "" },
{ device: "L4751", comment: "94ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4755", comment: "94ST:   작업완료", rtb: "" },
{ device: "L4756", comment: "94ST:   AIR     작업완료", rtb: "" },
{ device: "L4801", comment: "77ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4805", comment: "77ST:   작업완료", rtb: "" },
{ device: "L4806", comment: "77ST:   AIR     작업완료", rtb: "" },
{ device: "L4851", comment: "37ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4855", comment: "78ST:   작업완료", rtb: "" },
{ device: "L4856", comment: "78ST:   AIR     작업완료", rtb: "" },
{ device: "L4901", comment: "79ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4905", comment: "79ST:   작업완료", rtb: "" },
{ device: "L4906", comment: "79ST:   AIR     작업완료", rtb: "" },
{ device: "L4951", comment: "80ST:   TOTAL   작업완료", rtb: "" },
{ device: "L4955", comment: "80ST:   작업완료", rtb: "" },
{ device: "L4956", comment: "80ST:   AIR     작업완료", rtb: "" },
{ device: "L5551", comment: "38ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5555", comment: "38ST:   작업완료", rtb: "" },
{ device: "L5556", comment: "38ST:   AIR     작업완료", rtb: "" },
{ device: "L5601", comment: "39ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5604", comment: "39ST:   틸팅작업완료", rtb: "" },
{ device: "L5605", comment: "39ST:   LIFT작업완료", rtb: "" },
{ device: "L5606", comment: "39ST:   AIR     작업완료", rtb: "" },
{ device: "L5651", comment: "40ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5655", comment: "40ST:   작업완료", rtb: "" },
{ device: "L5656", comment: "40ST:   AIR     작업완료", rtb: "" },
{ device: "L5701", comment: "41ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5705", comment: "41ST:   작업완료", rtb: "" },
{ device: "L5706", comment: "41ST:   AIR     작업완료", rtb: "" },
{ device: "L5751", comment: "42ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5755", comment: "42ST:   작업완료", rtb: "" },
{ device: "L5756", comment: "42ST:   AIR     작업완료", rtb: "" },
{ device: "L5801", comment: "43ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5805", comment: "43ST:   작업완료", rtb: "" },
{ device: "L5806", comment: "43ST:   AIR     작업완료", rtb: "" },
{ device: "L5851", comment: "44ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5855", comment: "44ST:   작업완료", rtb: "" },
{ device: "L5856", comment: "44ST:   AIR     작업완료", rtb: "" },
{ device: "L5901", comment: "45ST:   TOTAL   작업완료", rtb: "" },
{ device: "L5905", comment: "45ST:   작업완료", rtb: "" },
{ device: "L5906", comment: "45ST:   AIR     작업완료", rtb: "" },
{ device: "L6001", comment: "R_01ST: TOTAL   작업완료", rtb: "" },
{ device: "L6005", comment: "R_01ST: 작업완료", rtb: "" },
{ device: "L6006", comment: "R_01ST: AIR     작업완료", rtb: "" },
{ device: "L6051", comment: "R_02ST: TOTAL   작업완료", rtb: "" },
{ device: "L6055", comment: "R_02ST: 작업완료", rtb: "" },
{ device: "L6056", comment: "R_02ST: AIR     작업완료", rtb: "" },
{ device: "L6101", comment: "R_03ST: TOTAL   작업완료", rtb: "" },
{ device: "L6105", comment: "R_03ST: 작업완료", rtb: "" },
{ device: "L6106", comment: "R_03ST: AIR     작업완료", rtb: "" },
{ device: "L6151", comment: "R_04ST: TOTAL   작업완료", rtb: "" },
{ device: "L6155", comment: "R_04ST: 작업완료", rtb: "" },
{ device: "L6156", comment: "R_04ST: AIR     작업완료", rtb: "" },
{ device: "L6201", comment: "R_05ST: TOTAL   작업완료", rtb: "" },
{ device: "L6204", comment: "R_05ST: UNCLAMP 작업완료", rtb: "" },
{ device: "L6205", comment: "R_05ST: UNCLAMP 작업완료", rtb: "" },
{ device: "L6206", comment: "R_05ST: AIR     작업완료", rtb: "" },
{ device: "L6251", comment: "R_06ST: TOTAL   작업완료", rtb: "" },
{ device: "L6255", comment: "R_06ST: 작업완료", rtb: "" },
{ device: "L6256", comment: "R_06ST: AIR     작업완료", rtb: "" },
{ device: "L6301", comment: "R_07ST: TOTAL   작업완료", rtb: "" },
{ device: "L6305", comment: "R_07ST: 작업완료", rtb: "" },
{ device: "L6306", comment: "R_07ST: AIR     작업완료", rtb: "" },
{ device: "L6351", comment: "R_08ST: TOTAL   작업완료", rtb: "" },
{ device: "L6355", comment: "R_08ST: 작업완료", rtb: "" },
{ device: "L6356", comment: "R_08ST: AIR     작업완료", rtb: "" },
{ device: "L6401", comment: "R_09ST: TOTAL   작업완료", rtb: "" },
{ device: "L6405", comment: "R_09ST: 작업완료", rtb: "" },
{ device: "L6406", comment: "R_09ST: AIR     작업완료", rtb: "" },
{ device: "L6451", comment: "R_10ST: TOTAL   작업완료", rtb: "" },
{ device: "L6454", comment: "R_10ST  인타운  작업완료", rtb: "" },
{ device: "L6455", comment: "R_10ST: 작업완료", rtb: "" },
{ device: "L6456", comment: "R_10ST: AIR     작업완료", rtb: "" },
{ device: "L6501", comment: "R_11ST: TOTAL   작업완료", rtb: "" },
{ device: "L6504", comment: "R_11ST: CLAMP   작업완료", rtb: "" },
{ device: "L6505", comment: "R_11ST: 작업완료", rtb: "" },
{ device: "L6506", comment: "R_11ST: AIR     작업완료", rtb: "" },
{ device: "L6551", comment: "R_12ST: TOTAL   작업완료", rtb: "" },
{ device: "L6555", comment: "R_12ST: 작업완료", rtb: "" },
{ device: "L6556", comment: "R_12ST: AIR     작업완료", rtb: "" },
{ device: "L6601", comment: "R_13ST: TOTAL   작업완료", rtb: "" },
{ device: "L6605", comment: "R_13ST: 작업완료", rtb: "" },
{ device: "L6606", comment: "R_13ST: AIR     작업완료", rtb: "" },
{ device: "L6651", comment: "R_14ST: TOTAL   작업완료", rtb: "" },
{ device: "L6655", comment: "R_14ST: 작업완료", rtb: "" },
{ device: "L6701", comment: "R_15ST: TOTAL   작업완료", rtb: "" },
{ device: "L6705", comment: "R_15ST: 작업완료", rtb: "" },
{ device: "L6751", comment: "R_16ST: TOTAL   작업완료", rtb: "" },
{ device: "L6755", comment: "R_16ST: 작업완료", rtb: "" },
{ device: "L6801", comment: "R_17ST: TOTAL   작업완료", rtb: "" },
{ device: "L6805", comment: "R_17ST: 작업완료", rtb: "" },
{ device: "L6851", comment: "R_18ST: TOTAL   작업완료", rtb: "" },
{ device: "L6855", comment: "R_18ST: 작업완료", rtb: "" },
{ device: "L6901", comment: "R_19ST: TOTAL   작업완료", rtb: "" },
{ device: "L6905", comment: "R_19ST: 작업완료", rtb: "" },
{ device: "L6951", comment: "R_20ST: TOTAL   작업완료", rtb: "" },
{ device: "L6955", comment: "R_20ST: 작업완료", rtb: "" },
{ device: "L7050", comment: "60ST:   폴딩장비작업완료", rtb: "" },
{ device: "L7150", comment: "68ST:   폴딩장비작업완료", rtb: "" },
{ device: "L7201", comment: "49ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7205", comment: "49ST:   작업완료", rtb: "" },
{ device: "L7206", comment: "49ST:   AIR     작업완료", rtb: "" },
{ device: "L7251", comment: "50ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7255", comment: "50ST:   작업완료", rtb: "" },
{ device: "L7256", comment: "50ST:   AIR     작업완료", rtb: "" },
{ device: "L7301", comment: "51ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7305", comment: "51ST:   작업완료", rtb: "" },
{ device: "L7306", comment: "51ST:   AIR     작업완료", rtb: "" },
{ device: "L7351", comment: "52ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7355", comment: "52ST:   작업완료", rtb: "" },
{ device: "L7356", comment: "52ST:   AIR     작업완료", rtb: "" },
{ device: "L7401", comment: "53ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7405", comment: "53ST:   작업완료", rtb: "" },
{ device: "L7406", comment: "53ST:   AIR     작업완료", rtb: "" },
{ device: "L7451", comment: "54ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7455", comment: "54ST:   작업완료", rtb: "" },
{ device: "L7456", comment: "54ST:   AIR     작업완료", rtb: "" },
{ device: "L7501", comment: "55ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7505", comment: "55ST:   작업완료", rtb: "" },
{ device: "L7506", comment: "55ST:   AIR     작업완료", rtb: "" },
{ device: "L7551", comment: "56ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7555", comment: "56ST:   작업완료", rtb: "" },
{ device: "L7556", comment: "56ST:   AIR     작업완료", rtb: "" },
{ device: "L7601", comment: "57ST:   TOTAL   작업완료", rtb: "" },
{ device: "L7605", comment: "58ST:   작업완료", rtb: "" },
{ device: "L7606", comment: "58ST:   AIR     작업완료", rtb: "" },
];