// data_x.js
const devicesx = [
{ device: "X0A40", comment: "76ST:   라이트  커튼센서", rtb: "" },
{ device: "X0A41", comment: "62ST:   T/TABLE 하강단", rtb: "" },
{ device: "X0A42", comment: "62ST:   T/TABLE 상승단", rtb: "" },
{ device: "X0A43", comment: "62ST:   T/TABLE 복귀단", rtb: "" },
{ device: "X0A44", comment: "62ST:   T/TABLE 회전단", rtb: "" },
{ device: "X0A45", comment: "65ST:   LIFTER  하강단", rtb: "" },
{ device: "X0A46", comment: "65ST:   LIFTER  상승단", rtb: "" },
{ device: "X0A47", comment: "60ST검사-> C/V  틸팅하강요구", rtb: "" },
{ device: "X0A48", comment: "62ST검사-> C/V  작업완료", rtb: "" },
{ device: "X0A49", comment: "62ST검사-> C/V  간섭없음", rtb: "" },
{ device: "X0A4A", comment: "62ST검사-> C/V  작업있음", rtb: "" },
{ device: "X0A4C", comment: "64ST검사-> C/V  작업완료", rtb: "" },
{ device: "X0A4D", comment: "64ST검사-> C/V  간섭없음", rtb: "" },
{ device: "X0A4E", comment: "64ST검사-> C/V  작업있음", rtb: "" },
{ device: "X0A60", comment: "66ST검사-> C/V  작업완료", rtb: "" },
{ device: "X0A61", comment: "66ST:   검사    간섭없음", rtb: "" },
{ device: "X0A62", comment: "66ST:   검사    작업있음", rtb: "" },
{ device: "X0A64", comment: "71ST검사-> C/V  작업완료", rtb: "" },
{ device: "X0A65", comment: "53ST검사-> C/V  간섭없음", rtb: "" },
{ device: "X0A66", comment: "53ST검사-> C/V  고장", rtb: "" },
{ device: "X0A67", comment: "53ST검사-> C/V  고장", rtb: "" },
{ device: "X0A68", comment: "65ST로봇-> C/V  작업완료", rtb: "" },
{ device: "X0A69", comment: "65ST:   로봇    간섭없음", rtb: "" },
{ device: "X0A6A", comment: "65ST:   로봇    작업있음", rtb: "" },
{ device: "X0A6B", comment: "65ST:   로봇    고장", rtb: "" },
{ device: "X0A6C", comment: "67ST로봇-> C/V  작업완료(Y45)", rtb: "" },
{ device: "X0A6D", comment: "67ST:   로봇    간섭없음", rtb: "" },
{ device: "X0A6E", comment: "75ST:   로봇    작었있음", rtb: "" },
{ device: "X0A6F", comment: "67ST:   로봇    고장", rtb: "" },
{ device: "X0AA0", comment: "89ST트랙      -> C/V납품위치N.G", rtb: "" },
{ device: "X0AA1", comment: "89ST트랙-> C/V  작업완료", rtb: "" },
{ device: "X0AA2", comment: "72ST트랙-> C/V  작업있음", rtb: "" },
{ device: "X0AA8", comment: "92ST:   로봇    작업완료", rtb: "" },
{ device: "X0AA9", comment: "92ST:   로봇간섭없음", rtb: "" },
{ device: "X0AE0", comment: "R_10ST: 서열PASS", rtb: "" },
{ device: "X0AE1", comment: "인타운  ->R_10ST서열작업완료", rtb: "" },
{ device: "X0AE2", comment: "R-11ST:   비상정지RPB", rtb: "" },
{ device: "X0AE3", comment: "R_12ST: 작업완료SW", rtb: "" },
{ device: "X0AE4", comment: "R_12ST: PASS SW", rtb: "" },
{ device: "X0AE5", comment: "검사기->C/V검사 완료", rtb: "" },
{ device: "X0AE6", comment: "리워크POS-G검사기원점-Y0D", rtb: "" },
{ device: "X0AE7", comment: "R_12ST:검사기작업사양신호TB09Y0E", rtb: "" },
{ device: "X0AE9", comment: "리워크   자동운전SW", rtb: "" },
{ device: "X0AEA", comment: "리워크   자동정지SW", rtb: "" },
{ device: "X0AEC", comment: "10ST:   원점완료SW", rtb: "" },
{ device: "X0AEF", comment: "R_13ST: 원점복귀SW", rtb: "" },
{ device: "X1000", comment: "MAIN    C/V_01  선택 'A'SEL", rtb: "" },
{ device: "X1001", comment: "MAIN    C/V_02  선택 'A'SEL", rtb: "" },
{ device: "X1002", comment: "MAIN    C/V_05  선택 'A'SEL", rtb: "" },
{ device: "X1003", comment: "MAIN    C/V_06  선택 'A'SEL", rtb: "" },
{ device: "X1004", comment: "MAIN    C/V_01  INV 'A' M1 S/W", rtb: "" },
{ device: "X1005", comment: "MAIN    C/V_01  INV 'A' M2 S/W", rtb: "" },
{ device: "X1006", comment: "MAIN    C/V_01  INV 'B' M1 S/W", rtb: "" },
{ device: "X1007", comment: "MAIN    C/V_01  INV 'B' M2 S/W", rtb: "" },
{ device: "X1008", comment: "MAIN    C/V_02  INV 'A' M1 S/W", rtb: "" },
{ device: "X1009", comment: "MAIN    C/V_02  INV 'A' M2 S/W", rtb: "" },
{ device: "X100A", comment: "MAIN    C/V_02  INV 'B' M1 S/W", rtb: "" },
{ device: "X100B", comment: "MAIN    C/V_02  INV 'B' M2 S/W", rtb: "" },
{ device: "X100D", comment: "SUB     PANEL   DC CP   TRIP", rtb: "" },
{ device: "X100E", comment: "SUB     PANEL   조명 CP TRIP", rtb: "" },
{ device: "X100F", comment: "SUB     PANEL   콘센트CPTRIP", rtb: "" },
{ device: "X1010", comment: "MAIN    C/V_03  INV 'A' M1 S/W", rtb: "" },
{ device: "X1011", comment: "MAIN    C/V_03  INV 'A' M2 S/W", rtb: "" },
{ device: "X1012", comment: "MAIN    C/V_03  INV 'B' M1 S/W", rtb: "" },
{ device: "X1013", comment: "MAIN    C/V_03  INV 'B' M2 S/W", rtb: "" },
{ device: "X1014", comment: "MAIN    C/V_04  INV 'A' M1 S/W", rtb: "" },
{ device: "X1015", comment: "MAIN    C/V_04  INV 'A' M2 S/W", rtb: "" },
{ device: "X1016", comment: "MAIN    C/V_04  INV 'B' M1 S/W", rtb: "" },
{ device: "X1017", comment: "MAIN    C/V_04  INV 'B' M2 S/W", rtb: "" },
{ device: "X1018", comment: "Main    C/V_1A  과부하", rtb: "" },
{ device: "X1019", comment: "Main    C/V 1B  과부하", rtb: "" },
{ device: "X101A", comment: "Main    C/V 2A  과부하", rtb: "" },
{ device: "X101B", comment: "Main    C/V 2B  과부하", rtb: "" },
{ device: "X101C", comment: "Main    C/V 5A  과부하", rtb: "" },
{ device: "X101D", comment: "Main    C/V 5B  과부하", rtb: "" },
{ device: "X101E", comment: "Main    C/V 6A  과부하", rtb: "" },
{ device: "X101F", comment: "Main    C/V 6B  과부하", rtb: "" },
{ device: "X106C", comment: "57ST로봇-> C/V  작업완료", rtb: "" },
{ device: "X1080", comment: "OP03;   MOTOR5  기동PB", rtb: "" },
{ device: "X1081", comment: "OP03;   MOTOR5  정지PB", rtb: "" },
{ device: "X1082", comment: "OP03;   MOTOR6  기동PB", rtb: "" },
{ device: "X1083", comment: "OP03;   MOTOR6  정지PB", rtb: "" },
{ device: "X108F", comment: "OP:03   CP Trip", rtb: "" },
{ device: "X10A4", comment: "75ST로봇-> C/V  작업완료", rtb: "" },
{ device: "X10A5", comment: "75ST로봇-> C/V  간섭없음", rtb: "" },
{ device: "X10E0", comment: "46ST:   MODE    자동SEL", rtb: "" },
{ device: "X10E1", comment: "46ST:   LIFTER  하강PB", rtb: "" },
{ device: "X10E2", comment: "46ST:   LIFTER  상승PB", rtb: "" },
{ device: "X10E3", comment: "46ST:   DIVERTERMOTOR ON정회전", rtb: "" },
{ device: "X10E4", comment: "47ST:   MODE    자동SEL", rtb: "" },
{ device: "X10E5", comment: "47ST:   MODE    자동SEL", rtb: "" },
{ device: "X10E6", comment: "47ST:   T/TABLE 상승PB", rtb: "" },
{ device: "X10E7", comment: "47ST:   T/TABLE 복귀PB", rtb: "" },
{ device: "X10E8", comment: "47ST:   T/TABLE 복귀PB", rtb: "" },
{ device: "X10E9", comment: "47ST:   T/TABLE 회전PB", rtb: "" },
{ device: "X10EC", comment: "47ST:   1 CYCLE PB", rtb: "" },
{ device: "X10ED", comment: "47ST:   원점복귀PB", rtb: "" },
{ device: "X10EF", comment: "Remote  Box_04-1CP Trip", rtb: "" },
{ device: "X10F1", comment: "38ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F2", comment: "39ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F3", comment: "40ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F4", comment: "41ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F5", comment: "42ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F6", comment: "43ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F7", comment: "44ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F8", comment: "45ST:   PALLET  도착센서", rtb: "" },
{ device: "X10F9", comment: "46ST:   PALLET  도착센서-1", rtb: "" },
{ device: "X10FA", comment: "46ST:   PALLET  도착센서-2", rtb: "" },
{ device: "X10FC", comment: "46ST:   LIFTER  하강단", rtb: "" },
{ device: "X10FD", comment: "46ST:   LIFTER  상승단", rtb: "" },
{ device: "X10FE", comment: "47ST:   PALLET  도착센서", rtb: "" },
{ device: "X10FF", comment: "47ST:   T/TABLE 하강단", rtb: "" },
{ device: "X1100", comment: "47ST:   T/TABLE 상승단", rtb: "" },
{ device: "X1101", comment: "47ST:   T/TABLE 복귀단", rtb: "" },
{ device: "X1102", comment: "47ST:   T/TABLE 회전단", rtb: "" },
{ device: "X1103", comment: "37ST:   PALLET  도착센서", rtb: "" },
{ device: "X1104", comment: "40ST:   비상정지RPB", rtb: "" },
{ device: "X1148", comment: "56ST    전극 전진SPB", rtb: "" },
{ device: "X1149", comment: "56ST    전극 후진SPB", rtb: "" },
{ device: "X11A0", comment: "48ST:   MODE    자동SEL", rtb: "" },
{ device: "X11A1", comment: "48ST:   DIVERTERMOTOR ON정회전PB", rtb: "" },
{ device: "X11A2", comment: "48ST:   DIVERTER하강PB", rtb: "" },
{ device: "X11A3", comment: "48ST:   DIVERTER정회전PB", rtb: "" },
{ device: "X11A4", comment: "54ST:   MODE    자동SEL", rtb: "" },
{ device: "X11A5", comment: "54ST:   LIFTER  하강PB", rtb: "" },
{ device: "X11A6", comment: "54ST:   LIFTER  상승PB", rtb: "" },
{ device: "X11A7", comment: "54ST:   PASS PB", rtb: "" },
{ device: "X11AE", comment: "61ST:   LIFTER  상승단", rtb: "" },
{ device: "X11AF", comment: "54ST:   원점복귀PB", rtb: "" },
{ device: "X11B0", comment: "48ST:   PALLET  도착센서-1", rtb: "" },
{ device: "X11B1", comment: "57ST:   PALLET  도착센서", rtb: "" },
{ device: "X11B2", comment: "48ST:   DIVERTER하강단", rtb: "" },
{ device: "X11B3", comment: "48ST:   DIVERTER상승단", rtb: "" },
{ device: "X11B4", comment: "49ST:   PALLET  도착센서", rtb: "" },
{ device: "X11B5", comment: "50ST:   PALLET  도착센서", rtb: "" },
{ device: "X11B6", comment: "51ST:   PALLET  도착센서", rtb: "" },
{ device: "X11B7", comment: "52ST:   PALLET  도착센서", rtb: "" },
{ device: "X11B8", comment: "53ST:   PALLET  도착센서", rtb: "" },
{ device: "X11B9", comment: "54ST:   PALLET  도착센서", rtb: "" },
{ device: "X11BA", comment: "54ST:   LIFTER  하강단", rtb: "" },
{ device: "X11BB", comment: "54ST:   LIFTER  상승단", rtb: "" },
{ device: "X11BC", comment: "55ST:   PALLET  도착센서", rtb: "" },
{ device: "X11BD", comment: "56ST:   PALLET  도착센서", rtb: "" },
{ device: "X11BE", comment: "56ST:   LIFTER  하강단", rtb: "" },
{ device: "X11BF", comment: "56ST:   LIFTER  상승단", rtb: "" },
{ device: "X11C0", comment: "53ST:   LIFTER  하강단", rtb: "" },
{ device: "X11C1", comment: "53ST:   LIFTER  상승단", rtb: "" },
{ device: "X11C3", comment: "54ST:   전극    후진단", rtb: "" },
{ device: "X11C4", comment: "54ST:   전극    전진단", rtb: "" },
{ device: "X11C5", comment: "54ST:   전극    후진PB", rtb: "" },
{ device: "X11C6", comment: "54ST:   전극    전진PB", rtb: "" },
{ device: "X11C7", comment: "52ST:   비상정지RPB", rtb: "" },
{ device: "X11C8", comment: "52ST:   LIFTER  상승단", rtb: "" },
{ device: "X11C9", comment: "52ST:   LIFTER  하강PB", rtb: "" },
{ device: "X11CA", comment: "52ST:   LIFTER  상승PB", rtb: "" },
{ device: "X11CB", comment: "52ST:   PASS    S/W", rtb: "" },
{ device: "X11CC", comment: "52ST:   MODE    자동SEL", rtb: "" },
{ device: "X11CD", comment: "52ST:   원점복귀PB", rtb: "" },
{ device: "X11CE", comment: "48ST:   PALLET  도착센서-2", rtb: "" },
{ device: "X11CF", comment: "Remote  Box_03-1CP Trip", rtb: "" },
{ device: "X11D0", comment: "52ST:   BARCODE 검사완료", rtb: "" },
{ device: "X11D4", comment: "54ST:   IMS     작업완료(검사완)", rtb: "" },
{ device: "X11D5", comment: "54ST:   IMS     검사모델(LIFT상)", rtb: "" },
{ device: "X11D6", comment: "54ST:   IMS     검사패스", rtb: "" },
{ device: "X11D7", comment: "원점", rtb: "" },
{ device: "X11D8", comment: "50ST:   MODE    자동SEL", rtb: "" },
{ device: "X11D9", comment: "50ST:   컨베어  PASS", rtb: "" },
{ device: "X11DA", comment: "50ST:   검사기->컨베어  작업완료", rtb: "" },
{ device: "X11DB", comment: "50ST:   검사기->컨베어  원점", rtb: "" },
{ device: "X11DC", comment: "50ST:   PASS SEL", rtb: "" },
{ device: "X11DE", comment: "61ST:   LIFTER  하강단", rtb: "" },
{ device: "X11DF", comment: "58ST:   PALLET  도착센서-2", rtb: "" },
{ device: "X1203", comment: "22ST:   AIR     SUPPLY  전진 S/W", rtb: "" },
{ device: "X1220", comment: "53ST:   MODE    자동SEL", rtb: "" },
{ device: "X1221", comment: "53ST:   LIFTER  상승PB", rtb: "" },
{ device: "X1222", comment: "53ST:   LIFTER  하강PB", rtb: "" },
{ device: "X1223", comment: "61ST:   검사기 작업완료", rtb: "" },
{ device: "X1224", comment: "53ST:   PASS PB", rtb: "" },
{ device: "X1225", comment: "53ST:   전극    전진PB", rtb: "" },
{ device: "X1226", comment: "53ST:   전극    후진PB", rtb: "" },
{ device: "X1227", comment: "53ST:   원점복귀PB", rtb: "" },
{ device: "X1228", comment: "53ST:   전극    후진단", rtb: "" },
{ device: "X1229", comment: "53ST:   전극    전진단", rtb: "" },
{ device: "X122A", comment: "56ST    전극 후진센서", rtb: "" },
{ device: "X122B", comment: "56ST    전극 전진센서", rtb: "" },
{ device: "X1230", comment: "61ST: 검사기 작업완료(INT:Y1C)", rtb: "" },
{ device: "X1231", comment: "61ST: 검사기 원점(INT:Y1D)", rtb: "" },
{ device: "X1232", comment: "61ST: 검사기 검사사양(INT:Y1E)", rtb: "" },
{ device: "X1233", comment: "61ST: SPARE(INT:Y1F)", rtb: "" },
{ device: "X1234", comment: "61ST:   MODE    자동SEL", rtb: "" },
{ device: "X1235", comment: "61ST:   LIFTER  상승PB", rtb: "" },
{ device: "X1236", comment: "61ST:   LIFTER  하강PB", rtb: "" },
{ device: "X1237", comment: "61ST:작업 (검사 실시)  S/S", rtb: "" },
{ device: "X1238", comment: "56ST:   실통풍  검사완료", rtb: "" },
{ device: "X1239", comment: "통풍->  56ST:   검사기  원점", rtb: "" },
{ device: "X123A", comment: "통풍->  56ST:   검사사양", rtb: "" },
{ device: "X123C", comment: "PODS->  59ST    작업완료", rtb: "" },
{ device: "X123D", comment: "검사기원점", rtb: "" },
{ device: "X123E", comment: "PODS->  59ST    검사사양", rtb: "" },
{ device: "X1260", comment: "49ST:AIRSUPPLY  전진단  [PX]", rtb: "" },
{ device: "X1261", comment: "49ST:AIRSUPPLY  후진단  [PX]", rtb: "" },
{ device: "X1262", comment: "49ST:   MODE    자동 S/W", rtb: "" },
{ device: "X1263", comment: "49ST:   AIR     SUPPLY  전진 S/W", rtb: "" },
{ device: "X1264", comment: "49ST:   AIR     SUPPLY  후진 S/W", rtb: "" },
{ device: "X1265", comment: "49ST:AIRSUPPLY  클램프  [SPB]", rtb: "" },
{ device: "X1266", comment: "49ST:AIRSUPPLY  언클램프[SPB]", rtb: "" },
{ device: "X1267", comment: "49ST:AIRSUPPLY  PASS[SPB]", rtb: "" },
{ device: "X161", comment: "자국DataLINK상태#02", rtb: "" },
{ device: "X163", comment: "타국DataLINK    상태#02", rtb: "" },
{ device: "X164", comment: "53ST검사-> C/V  작업완료", rtb: "" },
{ device: "X16F", comment: "CC-LINK Module  Ready   #02", rtb: "" },
{ device: "X19", comment: "이더넷  Ready On상태", rtb: "" },
{ device: "X1C", comment: "이더넷  알람 SIG", rtb: "" },
{ device: "X200", comment: "우렁이  임시접점", rtb: "" },
{ device: "X201", comment: "1~100ST STOPPER 하강 SW", rtb: "" },
{ device: "X203", comment: "임시접점DIVERTER정회전  ON SW", rtb: "" },
{ device: "X204", comment: "임시접점DIVERTER정회전   OFF SW", rtb: "" },
{ device: "X205", comment: "임시접점PASS SW", rtb: "" },
{ device: "X206", comment: "임시접점작업완료SW", rtb: "" },
{ device: "X207", comment: "임시접점LH 감지", rtb: "" },
{ device: "X21", comment: "자국DataLINK상태#1", rtb: "" },
{ device: "X210", comment: "임시접점DIVERTER상승단", rtb: "" },
{ device: "X220", comment: "CYCLE   TIME    1의 자리", rtb: "" },
{ device: "X224", comment: "CYCLE   TIME    10의 자리", rtb: "" },
{ device: "X228", comment: "CYCLE   TIME    100의   자리", rtb: "" },
{ device: "X23", comment: "타국DataLINK    상태#1", rtb: "" },
{ device: "X2B0", comment: "임시접점ROBOT   ->C/V   작업완료", rtb: "" },
{ device: "X2B1", comment: "임시접점ROBOT   ->C/V   간섭없음", rtb: "" },
{ device: "X2F", comment: "CC-LINK Module  Ready#01", rtb: "" },
{ device: "X300", comment: "OP:01   비상정지SW", rtb: "" },
{ device: "X301", comment: "OP:01   MODE    자동", rtb: "" },
{ device: "X302", comment: "OP:01   Mode    수동", rtb: "" },
{ device: "X303", comment: "OP:01   이상해제SW", rtb: "" },
{ device: "X304", comment: "OP:01   자동운전SW", rtb: "" },
{ device: "X305", comment: "OP:01   자동정지SW", rtb: "" },
{ device: "X306", comment: "OP:01   LampTest", rtb: "" },
{ device: "X30A", comment: "OP01:   01ST:   D/V 모터정지 SW", rtb: "" },
{ device: "X30B", comment: "OP01:   01ST:   D/V 모터정회전SW", rtb: "" },
{ device: "X30C", comment: "1 ~ 6 STStopper 하강 SW OP:01", rtb: "" },
{ device: "X30D", comment: "7~12 ST:STOPPER 하강 SW", rtb: "" },
{ device: "X30F", comment: "OP:01   CP Trip", rtb: "" },
{ device: "X310", comment: "OP:01   13~18ST STOPPER 하강 SW", rtb: "" },
{ device: "X311", comment: "OP:01   C/V_01  모터 OFFSW", rtb: "" },
{ device: "X312", comment: "OP:01   C/V_01  모터 ON SW", rtb: "" },
{ device: "X313", comment: "OP:01   C/V_03  모터 OFFSW", rtb: "" },
{ device: "X314", comment: "OP:01   C/V_03  모터 ON SW", rtb: "" },
{ device: "X315", comment: "OP:01   58~63ST STOPPER 하강 SW", rtb: "" },
{ device: "X316", comment: "OP:01   64~69ST STOPPER 하강 SW", rtb: "" },
{ device: "X317", comment: "OP:01   70~75ST STOPPER 하강 SW", rtb: "" },
{ device: "X318", comment: "OP01:   93ST    L/F 하강SW", rtb: "" },
{ device: "X319", comment: "OP01:   93ST    L/F 상승SW", rtb: "" },
{ device: "X31A", comment: "OP:01   76ST    D/V 모터정지 SW", rtb: "" },
{ device: "X31B", comment: "OP:01   76ST    D/V 모터정회전SW", rtb: "" },
{ device: "X31C", comment: "OP:01   C/V_04  모터 OFFSW", rtb: "" },
{ device: "X31D", comment: "OP:01   C/V_04  모터 ON SW", rtb: "" },
{ device: "X380", comment: "OP:02   비상정지SW", rtb: "" },
{ device: "X381", comment: "OP:02   MODE    자동", rtb: "" },
{ device: "X382", comment: "OP:02   Mode    수동", rtb: "" },
{ device: "X383", comment: "OP:02   이상해제SW", rtb: "" },
{ device: "X384", comment: "OP:02   자동운전SW", rtb: "" },
{ device: "X385", comment: "OP:02   자동정지SW", rtb: "" },
{ device: "X386", comment: "OP:02   LAMP    TEST SW", rtb: "" },
{ device: "X388", comment: "OP:02   19~24ST STOPPER 하강 SW", rtb: "" },
{ device: "X389", comment: "OP:02   25~30ST STOPPER 하강 SW", rtb: "" },
{ device: "X38A", comment: "31~36ST STOPPER 하강 SW", rtb: "" },
{ device: "X38B", comment: "OP:02   C/V_02  모터 OFFSW", rtb: "" },
{ device: "X38C", comment: "OP:02   C/V_01  모터 ON SW", rtb: "" },
{ device: "X38D", comment: "OP:02   C/V_02  모터 OFFSW", rtb: "" },
{ device: "X38E", comment: "OP:02   C/V_02  모터 ON SW", rtb: "" },
{ device: "X38F", comment: "OP:02   CP Trip", rtb: "" },
{ device: "X390", comment: "OP02:   46ST:   D/V 하강SW", rtb: "" },
{ device: "X391", comment: "OP02:   46ST:   D/V 상승SW", rtb: "" },
{ device: "X392", comment: "OP:02   46ST:   DIVERTER정지 SW", rtb: "" },
{ device: "X393", comment: "OP:02   46ST:   DIVERTER정회전SW", rtb: "" },
{ device: "X394", comment: "OP02:   58ST:   D/V 하강SW", rtb: "" },
{ device: "X395", comment: "OP02:   58ST:   D/V 상승SW", rtb: "" },
{ device: "X396", comment: "OP:02   48ST:   D/V 모터OFF SW", rtb: "" },
{ device: "X397", comment: "OP:02   48ST:   D/V 모터ON SW", rtb: "" },
{ device: "X398", comment: "OP:02   C/V_03  모터 OFFSW", rtb: "" },
{ device: "X399", comment: "OP:02   C/V_03  모터 ON SW", rtb: "" },
{ device: "X39A", comment: "39~44ST STOPPER 하강 SOL", rtb: "" },
{ device: "X39B", comment: "OP:02   45~51ST ST 하강 SW", rtb: "" },
{ device: "X39C", comment: "OP:02   52~57ST STOPPER 하강 SW", rtb: "" },
{ device: "X40", comment: "Main    Panel   제어전원ON", rtb: "" },
{ device: "X400", comment: "1ST:    MODE    자동 SW", rtb: "" },
{ device: "X401", comment: "01ST:   DIVERTERMOTOR   정회전SW", rtb: "" },
{ device: "X402", comment: "01ST:   DIVERTERMOTOR   역회전SW", rtb: "" },
{ device: "X403", comment: "01ST:   DIVERTER하강 SW", rtb: "" },
{ device: "X404", comment: "01ST:   DIVERTER상승 SW", rtb: "" },
{ device: "X405", comment: "07ST:   작업완료SW", rtb: "" },
{ device: "X406", comment: "06ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X407", comment: "06ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X408", comment: "05ST:   사용    PASS", rtb: "" },
{ device: "X409", comment: "05ST:   MODE    자동 SW", rtb: "" },
{ device: "X40A", comment: "05ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X40B", comment: "05ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X40C", comment: "06ST:   MODE    자동 SW", rtb: "" },
{ device: "X40D", comment: "06ST:   AIR     SUPPLY  후진 SW", rtb: "" },
{ device: "X40E", comment: "06ST:   AIR     SUPPLY  전진 SW", rtb: "" },
{ device: "X40F", comment: "06ST:   AIR     SUPPLY  ON SW", rtb: "" },
{ device: "X41", comment: "Main    Panel   비상정지SW", rtb: "" },
{ device: "X410", comment: "09ST:   MODE    자동 SW", rtb: "" },
{ device: "X411", comment: "09ST:   T/TABLE 하강 PB", rtb: "" },
{ device: "X412", comment: "09ST:   T/TABLE 상승 PB", rtb: "" },
{ device: "X413", comment: "06ST:   AIR     UNCLAMP 후진 SW", rtb: "" },
{ device: "X414", comment: "06ST:   AIR     UNCLAMP 전진 SW", rtb: "" },
{ device: "X415", comment: "09ST:   PASS SW", rtb: "" },
{ device: "X416", comment: "09ST:   작업완료SW", rtb: "" },
{ device: "X418", comment: "01ST:   투입 STP하강 SW", rtb: "" },
{ device: "X419", comment: "01ST:   투입 STP상승 SW", rtb: "" },
{ device: "X41A", comment: "01ST:   도착 STP하강 SW", rtb: "" },
{ device: "X41B", comment: "01ST:   도착 STP상승 SW", rtb: "" },
{ device: "X41C", comment: "6ST:    언락킹  1CYCLE  SW", rtb: "" },
{ device: "X41D", comment: "6ST:    락킹    1CYCLE  SW", rtb: "" },
{ device: "X41E", comment: "05ST:   작업완료SW", rtb: "" },
{ device: "X41F", comment: "Remote  Box01   CP Trip", rtb: "" },
{ device: "X42", comment: "Main    Panel   운전준비SW", rtb: "" },
{ device: "X420", comment: "1ST:    PALLET  도착단", rtb: "" },
{ device: "X421", comment: "01ST:   DIVERTER하강 Sen", rtb: "" },
{ device: "X422", comment: "01ST:   DIVERTER상승 Sen", rtb: "" },
{ device: "X423", comment: "1ST:    투입 STP하강 Sen", rtb: "" },
{ device: "X424", comment: "2ST:    PALLET  도착단", rtb: "" },
{ device: "X425", comment: "06ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X426", comment: "06ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X427", comment: "1ST:    도착 STP상승 Sen", rtb: "" },
{ device: "X428", comment: "03ST:   PALLET  도착단", rtb: "" },
{ device: "X429", comment: "04ST:   PALLET  도착단", rtb: "" },
{ device: "X42A", comment: "05ST:   LH 감지 Sen", rtb: "" },
{ device: "X42B", comment: "05ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X42C", comment: "05ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X42D", comment: "05ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X42E", comment: "05ST:   트랙안착감지    센서", rtb: "" },
{ device: "X42F", comment: "06ST:   PALLET  도착단", rtb: "" },
{ device: "X43", comment: "Main    Panel   MODE    자동S/W", rtb: "" },
{ device: "X430", comment: "07ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X431", comment: "06ST:   AIR     SUPPLY  후진_L", rtb: "" },
{ device: "X432", comment: "05ST:   AIR     SUPPLY  후진_R", rtb: "" },
{ device: "X433", comment: "6ST:    트랙이상감지", rtb: "" },
{ device: "X434", comment: "08ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X435", comment: "09ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X436", comment: "09ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X437", comment: "09ST:   T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X438", comment: "05ST:   RH 사양 감지", rtb: "" },
{ device: "X439", comment: "01ST:   0FF:1개 ON:1SET", rtb: "" },
{ device: "X43A", comment: "09ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X43B", comment: "06ST:   AIR     UNCLAMP 후진", rtb: "" },
{ device: "X43C", comment: "07ST:   AIR     SUPPLY  후진_R", rtb: "" },
{ device: "X43D", comment: "07ST:   AIR     SUPPLY  후진단", rtb: "" },
{ device: "X43F", comment: "MAIN    AIR ON", rtb: "" },
{ device: "X45", comment: "Main    자동운전SW", rtb: "" },
{ device: "X46", comment: "Main    자동정지SW", rtb: "" },
{ device: "X47", comment: "Main    Panel   이상해제SW", rtb: "" },
{ device: "X48", comment: "Main    Buzzer  Stop SW", rtb: "" },
{ device: "X480", comment: "11ST:   MODE    자동 SW", rtb: "" },
{ device: "X481", comment: "11ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X482", comment: "11ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X483", comment: "11ST:   Pass S/W", rtb: "" },
{ device: "X484", comment: "22ST:AIRSUPPLY  전진단  [PX]", rtb: "" },
{ device: "X485", comment: "11ST:   PASS SW", rtb: "" },
{ device: "X486", comment: "11ST:   T/TABLE 작업완료SW", rtb: "" },
{ device: "X487", comment: "22ST:AIRSUPPLY  후진단  [PX]", rtb: "" },
{ device: "X488", comment: "18ST:   MODE    자동 SW", rtb: "" },
{ device: "X489", comment: "15ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X48A", comment: "15ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X48B", comment: "15ST:   PASS SW", rtb: "" },
{ device: "X48C", comment: "18ST:   작업완료SW", rtb: "" },
{ device: "X48D", comment: "19ST:   비상정지RPB", rtb: "" },
{ device: "X48E", comment: "10ST:   자동 S/W", rtb: "" },
{ device: "X48F", comment: "10ST:AIRSUPPLY  전진    [SPB]", rtb: "" },
{ device: "X49", comment: "Main    Panel   LampTest", rtb: "" },
{ device: "X490", comment: "23ST:   MODE    자동 SW", rtb: "" },
{ device: "X491", comment: "20ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X492", comment: "20ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X493", comment: "20ST:   PASS SW", rtb: "" },
{ device: "X494", comment: "20ST:   작업완료SW", rtb: "" },
{ device: "X495", comment: "10ST:AIRSUPPLY  후진    [SPB]", rtb: "" },
{ device: "X496", comment: "26ST:   MODE    자동 SW", rtb: "" },
{ device: "X497", comment: "26ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X498", comment: "26ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X499", comment: "22ST:   TILT    하강 SW", rtb: "" },
{ device: "X49A", comment: "22ST:   TILT    상승 SW", rtb: "" },
{ device: "X49B", comment: "22ST:   TILTING PASS SW", rtb: "" },
{ device: "X49C", comment: "22ST:   작업완료SW", rtb: "" },
{ device: "X49D", comment: "30ST:   LH 사양 감지", rtb: "" },
{ device: "X49E", comment: "30ST:   RH 사양 감지", rtb: "" },
{ device: "X49F", comment: "Remote  Box_02  CP Trip", rtb: "" },
{ device: "X4A0", comment: "10ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4A1", comment: "11ST:   T/TABLE 하강 SeN", rtb: "" },
{ device: "X4A2", comment: "11ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X4A3", comment: "11ST:   T/TABLE 복귀 Sen", rtb: "" },
{ device: "X4A4", comment: "18ST    RH감지", rtb: "" },
{ device: "X4A5", comment: "18ST    LH감지", rtb: "" },
{ device: "X4A6", comment: "11ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4A7", comment: "12ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4A8", comment: "13ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4A9", comment: "14ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4AA", comment: "15ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4AB", comment: "15ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X4AC", comment: "15ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X4AD", comment: "18ST:   BACK SUB감지센서", rtb: "" },
{ device: "X4AE", comment: "16ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4AF", comment: "17ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4B0", comment: "18ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4B1", comment: "19ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4B2", comment: "20ST:   PALLET  도착단", rtb: "" },
{ device: "X4B3", comment: "20ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X4B4", comment: "20ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X4B5", comment: "10ST:   AIR     SUPPLY  클램프", rtb: "" },
{ device: "X4B6", comment: "21ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4B7", comment: "22ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4B8", comment: "26ST:   LIFTER  하강단", rtb: "" },
{ device: "X4B9", comment: "26ST:   LIFTER  상승단", rtb: "" },
{ device: "X4BA", comment: "26ST:   TILT    하강단", rtb: "" },
{ device: "X4BB", comment: "26ST:   TILT    상승단", rtb: "" },
{ device: "X4BC", comment: "10ST:   AIR     SUPPLY  언클램프", rtb: "" },
{ device: "X4BD", comment: "23ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4BE", comment: "24ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X4BF", comment: "10ST:AIRSUPPLY  PASS[SPB]", rtb: "" },
{ device: "X4E0", comment: "07ST:   MODE    자동 SW", rtb: "" },
{ device: "X4E1", comment: "07ST:   AIR     SUPPLY  후진 SW", rtb: "" },
{ device: "X4E2", comment: "07ST:    AIR     SUPPLY  전진 SW", rtb: "" },
{ device: "X4E3", comment: "07ST:   AIR     SUPPLY  후진 SW", rtb: "" },
{ device: "X4E4", comment: "07ST:   AIR     UNCLAMP 전진 SW", rtb: "" },
{ device: "X4E5", comment: "07ST:   AIR     SUPPLY  ON SW", rtb: "" },
{ device: "X4E6", comment: "07ST:   지그    클램프PB", rtb: "" },
{ device: "X4E7", comment: "07ST:   지그    언클램프PB", rtb: "" },
{ device: "X4E8", comment: "07ST:   원점복귀SW", rtb: "" },
{ device: "X4E9", comment: "07ST:   작업완료 S/W", rtb: "" },
{ device: "X4EA", comment: "15백서브라인  1 안전센서감지P17", rtb: "" },
{ device: "X4EB", comment: "15백서브라인  2 안전센서감지P17", rtb: "" },
{ device: "X4EC", comment: "15백서브라인1   안전센서감지P13", rtb: "" },
{ device: "X4ED", comment: "15백서브라인2   안전센서감지P13", rtb: "" },
{ device: "X4EE", comment: "10ST:AIRSUPPLY  전진단  [PX]", rtb: "" },
{ device: "X4EF", comment: "10ST:AIRSUPPLY  후진단  [PX]", rtb: "" },
{ device: "X4F", comment: "CYCLE   TIME    설정완료SW", rtb: "" },
{ device: "X50", comment: "MAIN    C/V_01  'A' 선택", rtb: "" },
{ device: "X500", comment: "31ST:   MODE    자동 SW", rtb: "" },
{ device: "X501", comment: "31ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X502", comment: "31ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X503", comment: "31ST:   T/TABLE 복귀 SW", rtb: "" },
{ device: "X504", comment: "31ST:   T/TABLE 좌회전  SW", rtb: "" },
{ device: "X505", comment: "29ST:   비상정지RPB", rtb: "" },
{ device: "X506", comment: "22ST:   MODE    자동 S/W", rtb: "" },
{ device: "X507", comment: "22ST:   AIR     SUPPLY  전진 S/W", rtb: "" },
{ device: "X508", comment: "22ST:   AIR     SUPPLY  후진 S/W", rtb: "" },
{ device: "X509", comment: "22ST:AIRSUPPLY  클램프  [SPB]", rtb: "" },
{ device: "X50A", comment: "38ST:   MODE    자동 SW", rtb: "" },
{ device: "X50B", comment: "38ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X50C", comment: "38ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X50D", comment: "38ST:   T/TABLE 회전 S/W", rtb: "" },
{ device: "X50E", comment: "38ST:   T/TABLE 복귀 S/W", rtb: "" },
{ device: "X50F", comment: "Remote  Box_03  CP Trip", rtb: "" },
{ device: "X51", comment: "MAIN    C/V_01  'B' 선택", rtb: "" },
{ device: "X510", comment: "39ST:   LIFTER  하강단  SEN", rtb: "" },
{ device: "X511", comment: "39ST:   LIFTER  상승단  SEN", rtb: "" },
{ device: "X512", comment: "39ST:   TILT    하강단", rtb: "" },
{ device: "X513", comment: "39ST:   TILT    상승단", rtb: "" },
{ device: "X514", comment: "44ST:   자동모드SW", rtb: "" },
{ device: "X515", comment: "34 PASS", rtb: "" },
{ device: "X516", comment: "44ST:   작업완료SW", rtb: "" },
{ device: "X517", comment: "46ST:   MODE    자동 SW", rtb: "" },
{ device: "X518", comment: "46ST:   DIVERTER정회전  ON SW", rtb: "" },
{ device: "X519", comment: "46ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X51A", comment: "46ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X51B", comment: "47ST:   MODE    자동 SW", rtb: "" },
{ device: "X51C", comment: "47ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X51D", comment: "47ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X51E", comment: "47ST:   T/TABLE 복귀 SW", rtb: "" },
{ device: "X51F", comment: "47ST:   T/TABLE 회전 SW", rtb: "" },
{ device: "X52", comment: "MAIN    C/V_03  선택 'A'SW", rtb: "" },
{ device: "X520", comment: "25ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X521", comment: "31ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X522", comment: "31ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X523", comment: "31ST:   T/TABLE 복귀단", rtb: "" },
{ device: "X524", comment: "31ST:   T/TABLE 회전단", rtb: "" },
{ device: "X525", comment: "22ST:AIRSUPPLY  언클램프[SPB]", rtb: "" },
{ device: "X526", comment: "26ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X527", comment: "27ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X528", comment: "28ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X529", comment: "29ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X52A", comment: "38ST:   T/TABLE 하강단", rtb: "" },
{ device: "X52B", comment: "38ST:   T/TABLE 상승단", rtb: "" },
{ device: "X52C", comment: "38ST:   T/TABLE 복귀단", rtb: "" },
{ device: "X52D", comment: "38ST:   T/TABLE 회전단", rtb: "" },
{ device: "X52E", comment: "28ST:   RH 사양 감지", rtb: "" },
{ device: "X52F", comment: "30ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X53", comment: "MAIN    C/V_03  선택 'B'SW", rtb: "" },
{ device: "X530", comment: "31ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X531", comment: "32ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X532", comment: "33ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X533", comment: "34ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X534", comment: "35ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X535", comment: "36ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X536", comment: "22ST:AIRSUPPLY  PASS[SPB]", rtb: "" },
{ device: "X537", comment: "36ST:   L,R감지 센서", rtb: "" },
{ device: "X538", comment: "36ST:   L,R감지 LS", rtb: "" },
{ device: "X539", comment: "46ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X53A", comment: "28ST:   LH 사양 감지", rtb: "" },
{ device: "X53B", comment: "47ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X53C", comment: "47ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X53D", comment: "47ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X53E", comment: "47ST:   T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X53F", comment: "47ST:   T/TABLE 회전단  Sen", rtb: "" },
{ device: "X54", comment: "MAIN    C/V_03  선택 'A'SW", rtb: "" },
{ device: "X55", comment: "MAIN    C/V_03  선택 'B'SW", rtb: "" },
{ device: "X56", comment: "MAIN    C/V_04  선택 'A'SW", rtb: "" },
{ device: "X57", comment: "MAIN    C/V_04  선택 'B'SW", rtb: "" },
{ device: "X580", comment: "65ST:   RH감지단", rtb: "" },
{ device: "X581", comment: "65ST:   LH감지단", rtb: "" },
{ device: "X582", comment: "65ST:   SEAT    감지", rtb: "" },
{ device: "X583", comment: "48ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X584", comment: "60ST:   TILT 상승SW", rtb: "" },
{ device: "X585", comment: "58ST:   MODE    자동 SW", rtb: "" },
{ device: "X586", comment: "58ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X587", comment: "58ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X588", comment: "56ST:   MODE    자동 SW", rtb: "" },
{ device: "X589", comment: "59ST:   T/TABLE 하강PB", rtb: "" },
{ device: "X58A", comment: "59ST:   T/TABLE 상승PB", rtb: "" },
{ device: "X58B", comment: "56ST:   작업완료PB", rtb: "" },
{ device: "X58C", comment: "56ST:   PASS PB", rtb: "" },
{ device: "X58D", comment: "59ST:   MODE    자동 SW", rtb: "" },
{ device: "X58E", comment: "59ST:   LIFTER  하강PB", rtb: "" },
{ device: "X58F", comment: "59ST:   LIFTER  상승PB", rtb: "" },
{ device: "X590", comment: "62ST:   MODE    자동SEL", rtb: "" },
{ device: "X591", comment: "62ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X592", comment: "62ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X593", comment: "62ST:   T/TABLE 복귀S/W", rtb: "" },
{ device: "X594", comment: "62ST:   T/TABLE 회전 S/W", rtb: "" },
{ device: "X595", comment: "62ST:   PASS SW", rtb: "" },
{ device: "X596", comment: "62ST:   작업완료SW", rtb: "" },
{ device: "X597", comment: "60ST:   TILT 상승SW", rtb: "" },
{ device: "X598", comment: "64ST:   MODE    자동 SW", rtb: "" },
{ device: "X599", comment: "65ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X59A", comment: "65ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X59B", comment: "64ST:   TILT    하강 SW", rtb: "" },
{ device: "X59C", comment: "65ST:   PASS SW", rtb: "" },
{ device: "X59D", comment: "64ST:   PASS SW", rtb: "" },
{ device: "X59E", comment: "64ST:   작업완료SW", rtb: "" },
{ device: "X59F", comment: "Remote  Box_04  CP Trip", rtb: "" },
{ device: "X5A0", comment: "60ST:   비상정지RPB", rtb: "" },
{ device: "X5A1", comment: "48ST:   DIVERTER하강 Sen", rtb: "" },
{ device: "X5A2", comment: "48ST:   DIVERTER상승 Sen", rtb: "" },
{ device: "X5A4", comment: "58ST:   PALLET  도착센서-1", rtb: "" },
{ device: "X5A5", comment: "59ST:  작업완료 S/W", rtb: "" },
{ device: "X5A6", comment: "58ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X5A8", comment: "59ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5A9", comment: "59ST:   LIFTER  하강단", rtb: "" },
{ device: "X5AA", comment: "59ST:   LIFTER  상승단", rtb: "" },
{ device: "X5AB", comment: "59ST:   TILT    하강단", rtb: "" },
{ device: "X5AC", comment: "59ST:   TILT    상승단", rtb: "" },
{ device: "X5AD", comment: "60ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5AE", comment: "60ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X5AF", comment: "60ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X5B0", comment: "61ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5B1", comment: "60ST:   TILT    하강단", rtb: "" },
{ device: "X5B2", comment: "60ST:   TILT    상승단", rtb: "" },
{ device: "X5B3", comment: "62ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5B4", comment: "62ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X5B5", comment: "62ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X5B6", comment: "62ST:   TILT    하강 Sen", rtb: "" },
{ device: "X5B7", comment: "62ST:   TILT    상승 Sen", rtb: "" },
{ device: "X5B9", comment: "63ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5BA", comment: "64ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5BB", comment: "64ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X5BC", comment: "64ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X5BD", comment: "64ST:   TILT    하강 Sen", rtb: "" },
{ device: "X5BE", comment: "64ST:   TILT    상승 Sen", rtb: "" },
{ device: "X5BF", comment: "65ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X5E", comment: "Main    Input   Card  CPTrip", rtb: "" },
{ device: "X5E0", comment: "49ST:AIRSUPPLY  전진단  [PX]", rtb: "" },
{ device: "X5E1", comment: "49ST:AIRSUPPLY  후진단  [PX]", rtb: "" },
{ device: "X5E2", comment: "49ST:   MODE    자동 S/W", rtb: "" },
{ device: "X5E3", comment: "49ST:AIRSUPPLY  전진    [SPB]", rtb: "" },
{ device: "X5E4", comment: "49ST:AIRSUPPLY  후진    [SPB]", rtb: "" },
{ device: "X5E5", comment: "49ST:AIRSUPPLY  클램프  [SPB]", rtb: "" },
{ device: "X5E6", comment: "49ST:AIRSUPPLY  언클램프[SPB]", rtb: "" },
{ device: "X5F", comment: "Panel   OutPut  CARD    CP Trip", rtb: "" },
{ device: "X60", comment: "1ST     DiverterMotor   과부하", rtb: "" },
{ device: "X600", comment: "67ST:   MODE    자동 SW", rtb: "" },
{ device: "X601", comment: "67ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X602", comment: "67ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X603", comment: "67ST:   PASS SW", rtb: "" },
{ device: "X604", comment: "67ST:   LIFTER  하강단", rtb: "" },
{ device: "X605", comment: "67ST:   LIFTER  상승단", rtb: "" },
{ device: "X606", comment: "66ST:   작업완료SW", rtb: "" },
{ device: "X608", comment: "69ST:   MODE    자동 SW", rtb: "" },
{ device: "X609", comment: "69ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X60A", comment: "67ST:   RH 감지단", rtb: "" },
{ device: "X60B", comment: "67ST:   LH 감지단", rtb: "" },
{ device: "X60C", comment: "69ST:   T/TABLE 회전 SW", rtb: "" },
{ device: "X60D", comment: "67ST:   SEAT    감지", rtb: "" },
{ device: "X60E", comment: "71ST:   PALLET  하강 SW", rtb: "" },
{ device: "X60F", comment: "71ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X61", comment: "46ST    DiverterMotor   과부하", rtb: "" },
{ device: "X610", comment: "73ST:   MODE    자동 SW", rtb: "" },
{ device: "X611", comment: "73ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X612", comment: "73ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X614", comment: "75ST:   MODE    자동 SW", rtb: "" },
{ device: "X615", comment: "75ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X616", comment: "75ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X617", comment: "스팀    로보트  안전센서감지1", rtb: "" },
{ device: "X618", comment: "스팀    로보트  안전센서감지2", rtb: "" },
{ device: "X619", comment: "71ST:   PASS SW", rtb: "" },
{ device: "X61A", comment: "71ST:   작업완료SW", rtb: "" },
{ device: "X61B", comment: "65ST:   PASS SW", rtb: "" },
{ device: "X61C", comment: "67ST:   작업완료", rtb: "" },
{ device: "X61D", comment: "75ST:   PASS SW", rtb: "" },
{ device: "X61E", comment: "75ST:   작업완료SW", rtb: "" },
{ device: "X61F", comment: "Remote  Box_05  CP Trip", rtb: "" },
{ device: "X62", comment: "Main    C/V_1A  과부하", rtb: "" },
{ device: "X620", comment: "66ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X621", comment: "66ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X622", comment: "66ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X623", comment: "66ST:   TILT    하강 Sen", rtb: "" },
{ device: "X624", comment: "66ST:   TILT    상승 Sen", rtb: "" },
{ device: "X626", comment: "67ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X627", comment: "68ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X628", comment: "69ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X629", comment: "69ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X62A", comment: "69ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X62B", comment: "51ST    T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X62C", comment: "69ST:   T/TABLE 회전단  Sen", rtb: "" },
{ device: "X62E", comment: "70ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X63", comment: "Main    C/V_1B  과부하", rtb: "" },
{ device: "X630", comment: "71ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X631", comment: "70ST:   PALLET  도착단", rtb: "" },
{ device: "X632", comment: "71ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X633", comment: "53ST:   SEAT감지", rtb: "" },
{ device: "X634", comment: "72ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X635", comment: "73ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X636", comment: "73ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X637", comment: "73ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X638", comment: "73ST:   SEAT    감지 Sen", rtb: "" },
{ device: "X63A", comment: "74ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X63B", comment: "75ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X63C", comment: "75ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X63D", comment: "75ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X63E", comment: "75ST:   작업", rtb: "" },
{ device: "X63F", comment: "76ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X64", comment: "Main    C/V 2A  과부하", rtb: "" },
{ device: "X65", comment: "Main    C/V 2B  과부하", rtb: "" },
{ device: "X66", comment: "48ST    DiverterMotor   과부하", rtb: "" },
{ device: "X67", comment: "70ST    DiverterMotor   과부하", rtb: "" },
{ device: "X68", comment: "73ST    DiverterMotor   과부하", rtb: "" },
{ device: "X680", comment: "스팀로봇1,2 패스", rtb: "" },
{ device: "X684", comment: "82공정   패스", rtb: "" },
{ device: "X685", comment: "82ST:   공정정지SEL", rtb: "" },
{ device: "X686", comment: "80ST:   MODE    자동 SW", rtb: "" },
{ device: "X687", comment: "82ST:   자동/수동", rtb: "" },
{ device: "X688", comment: "79ST:   MODE    자동 SW", rtb: "" },
{ device: "X689", comment: "79ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X68A", comment: "79ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X68B", comment: "79ST:   T/TABLE 복귀단  SW", rtb: "" },
{ device: "X68C", comment: "79ST:   T/TABLE 회전단  SW", rtb: "" },
{ device: "X68D", comment: "79ST:   T/TABLE PASS SW", rtb: "" },
{ device: "X68E", comment: "85ST:   LH 사양 감지", rtb: "" },
{ device: "X68F", comment: "85ST:   RH 사양 감지", rtb: "" },
{ device: "X69", comment: "Main    C/V_3A  Motor   과부하", rtb: "" },
{ device: "X690", comment: "87ST:   MODE    자동 SW", rtb: "" },
{ device: "X691", comment: "87ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X692", comment: "87ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X693", comment: "87ST:   T/TABLE 복귀PB", rtb: "" },
{ device: "X694", comment: "87ST:   T/TABLE 회전PB", rtb: "" },
{ device: "X695", comment: "87ST:   PASS SW", rtb: "" },
{ device: "X696", comment: "86ST:   OK SW", rtb: "" },
{ device: "X697", comment: "86ST:   NG SW", rtb: "" },
{ device: "X6A", comment: "Main    C/V_3B  Motor   과부하", rtb: "" },
{ device: "X6A0", comment: "77ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6A3", comment: "77ST:   SEAT감지", rtb: "" },
{ device: "X6A5", comment: "78ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6A8", comment: "78ST:   SEAT감지", rtb: "" },
{ device: "X6AA", comment: "79ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6AB", comment: "79ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X6AC", comment: "79ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X6AD", comment: "79ST:   T/TABLE 복귀단  센서", rtb: "" },
{ device: "X6AE", comment: "79ST:   T/TABLE 회전단  센서", rtb: "" },
{ device: "X6B", comment: "76ST    DiverterMotor   과부하", rtb: "" },
{ device: "X6B0", comment: "80ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6B1", comment: "81ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6B2", comment: "82ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6B3", comment: "83ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6B4", comment: "84ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6B7", comment: "85ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X6B8", comment: "87ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X6B9", comment: "87ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X6BA", comment: "87ST:   T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X6BB", comment: "87ST:   T/TABLE 회전단  Sen", rtb: "" },
{ device: "X6BE", comment: "85ST:   LH 감지 센서", rtb: "" },
{ device: "X6BF", comment: "85ST:   RH 감지 센서", rtb: "" },
{ device: "X6C", comment: "Main    C/V_4A  Motor   과부하", rtb: "" },
{ device: "X6D", comment: "Main    C/V_4B  Motor   과부하", rtb: "" },
{ device: "X6E", comment: "Repair  CV_1    Motor   과부하", rtb: "" },
{ device: "X6F", comment: "R02ST   DiverterMotor   과부하", rtb: "" },
{ device: "X70", comment: "R03ST   DiverterMotor   과부하", rtb: "" },
{ device: "X700", comment: "86ST:   MODE    자동SEL", rtb: "" },
{ device: "X701", comment: "86ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X702", comment: "86ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X703", comment: "86ST:   T/TABLE 복귀단  SW", rtb: "" },
{ device: "X704", comment: "86ST:   T/TABLE 회전단  SW", rtb: "" },
{ device: "X705", comment: "86ST:   서열PASSSW", rtb: "" },
{ device: "X706", comment: "86ST:   OK SW", rtb: "" },
{ device: "X707", comment: "88ST:   NG SW", rtb: "" },
{ device: "X708", comment: "88ST:   MODE    자동 SW", rtb: "" },
{ device: "X709", comment: "88ST:   D/V 모터정회전  SW", rtb: "" },
{ device: "X70A", comment: "88ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X70B", comment: "88ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X70C", comment: "89ST:   MODE    자동 SW", rtb: "" },
{ device: "X70D", comment: "89ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X70E", comment: "89ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X70F", comment: "Remote  Box_07  CP Trip", rtb: "" },
{ device: "X71", comment: "Repair  CV_02   Motor   과부하", rtb: "" },
{ device: "X710", comment: "90ST:   MODE    자동 SW", rtb: "" },
{ device: "X711", comment: "90ST:   D/V 모터정회전  SW", rtb: "" },
{ device: "X712", comment: "90ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X713", comment: "90ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X714", comment: "92ST:   MODE    자동 SW", rtb: "" },
{ device: "X715", comment: "92ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X716", comment: "92ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X717", comment: "93ST:   MODE    자동 SW", rtb: "" },
{ device: "X718", comment: "93ST:   D/V 모터정회전  SW", rtb: "" },
{ device: "X719", comment: "93ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X71A", comment: "93ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X71B", comment: "94ST:   MODE    자동 SW", rtb: "" },
{ device: "X71C", comment: "94ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X71D", comment: "94ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X71E", comment: "94ST:   T/TABLE 복귀 SW", rtb: "" },
{ device: "X71F", comment: "94ST:   T/TABLE 회전단  SW", rtb: "" },
{ device: "X72", comment: "R06ST   DiverterMotor   과부하", rtb: "" },
{ device: "X720", comment: "86ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X721", comment: "86ST:   T/TABLE 하강 Sen", rtb: "" },
{ device: "X722", comment: "86ST:   T/TABLE 상승 Sen", rtb: "" },
{ device: "X723", comment: "86ST:   T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X724", comment: "86ST:   T/TABLE 회전단  Sen", rtb: "" },
{ device: "X725", comment: "87ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X726", comment: "88ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X727", comment: "88ST:   DIVERTER하강 Sen", rtb: "" },
{ device: "X728", comment: "88ST:   DIVERTER상승 Sen", rtb: "" },
{ device: "X729", comment: "89ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X72A", comment: "89ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X72B", comment: "89ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X72C", comment: "89ST:   SEAT감지", rtb: "" },
{ device: "X72D", comment: "90ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X72E", comment: "90ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X72F", comment: "90ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X73", comment: "Repair  CV_03   Motor   과부하", rtb: "" },
{ device: "X730", comment: "91ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X731", comment: "92ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X732", comment: "92ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X733", comment: "92ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X734", comment: "92ST:   제품감지Sen", rtb: "" },
{ device: "X735", comment: "91ST:   AIR     SUPPLY_L후진 Sen", rtb: "" },
{ device: "X736", comment: "91ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X737", comment: "93ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X738", comment: "93ST:   LIFTER  하강 Sen", rtb: "" },
{ device: "X739", comment: "93ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X73A", comment: "94ST:   PALLET  도착 Sen", rtb: "" },
{ device: "X73B", comment: "94ST:   T/TABLE 하강 SW", rtb: "" },
{ device: "X73C", comment: "94ST:   T/TABLE 상승 SW", rtb: "" },
{ device: "X73D", comment: "94ST:   T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X73E", comment: "94ST:   T/TABLE 회전단  Sen", rtb: "" },
{ device: "X73F", comment: "91ST:   LIFTER  상승 Sen", rtb: "" },
{ device: "X74", comment: "R09ST   DiverterMotor   과부하", rtb: "" },
{ device: "X75", comment: "Repair  CV_04   Motor   과부하", rtb: "" },
{ device: "X76", comment: "지그교환LIFT D/VMotor   과부하", rtb: "" },
{ device: "X760", comment: "92ST:   LH 감지 Sen", rtb: "" },
{ device: "X761", comment: "92ST:   RH 감지 Sen", rtb: "" },
{ device: "X762", comment: "89ST:   PASS    SW", rtb: "" },
{ device: "X763", comment: "89ST:   작업완료SW", rtb: "" },
{ device: "X764", comment: "91ST:   AIR     UNCLAMP 후진 SW", rtb: "" },
{ device: "X765", comment: "91ST:   AIR     UNCLAMP 전진 SW", rtb: "" },
{ device: "X766", comment: "91ST:   AIR     UNCLAMP ON SW", rtb: "" },
{ device: "X767", comment: "92ST:   PALLET  지그들림센서", rtb: "" },
{ device: "X768", comment: "91ST:   작업완료SW92ST:   PALLET", rtb: "" },
{ device: "X769", comment: "92ST:   PALLET  지그들림센서", rtb: "" },
{ device: "X76A", comment: "92ST:   PALLET  지그들림센서", rtb: "" },
{ device: "X780", comment: "R_02ST: MODE    자동 SW", rtb: "" },
{ device: "X781", comment: "R_02ST: D/V 모터정회전  SW", rtb: "" },
{ device: "X782", comment: "R_02ST: LIFTER  하강 SW", rtb: "" },
{ device: "X783", comment: "R_02ST: LIFTER  상승 SW", rtb: "" },
{ device: "X785", comment: "R_03ST: MODE    자동 S/W", rtb: "" },
{ device: "X786", comment: "R_03ST: D/V 모터정회전  SW", rtb: "" },
{ device: "X787", comment: "R_03ST: LIFTER  하강 SW", rtb: "" },
{ device: "X788", comment: "R_03ST: LIFTER  상승 SW", rtb: "" },
{ device: "X78A", comment: "R_04ST: MODE    자동 SW", rtb: "" },
{ device: "X78B", comment: "R_04ST: T/TABLE 하강 W", rtb: "" },
{ device: "X78C", comment: "R_04ST: T/TABLE 상승 SW", rtb: "" },
{ device: "X78D", comment: "R_04ST: T/TABLE 복귀단  SW", rtb: "" },
{ device: "X78E", comment: "R_04ST: T/TABLE 회전단  SW", rtb: "" },
{ device: "X78F", comment: "R_04ST  PASS SW", rtb: "" },
{ device: "X790", comment: "R_06ST: MODE    자동 SW", rtb: "" },
{ device: "X791", comment: "R_06ST: D/V 모터정회전  SW", rtb: "" },
{ device: "X792", comment: "R_06ST: LIFTER  하강 SW", rtb: "" },
{ device: "X793", comment: "R_06ST: LIFTER  상승 SW", rtb: "" },
{ device: "X797", comment: "R_04ST: 원점복귀SW", rtb: "" },
{ device: "X79A", comment: "R_05ST: 자동    MODE SW", rtb: "" },
{ device: "X79B", comment: "R_05ST: AIR     UNCLAMP 후진 SW", rtb: "" },
{ device: "X79C", comment: "R_05ST: AIR     UNCLAMP 전진 SW", rtb: "" },
{ device: "X79D", comment: "R_05ST: AIR     UNCLAMP ON SW", rtb: "" },
{ device: "X79E", comment: "R_04ST  PASS SW", rtb: "" },
{ device: "X79F", comment: "Remote  Box_08  CP Trip", rtb: "" },
{ device: "X7A0", comment: "R_01ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7A1", comment: "R_02ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7A2", comment: "R_02ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7A3", comment: "R_02ST: LIFTER  하강 Sen", rtb: "" },
{ device: "X7A4", comment: "R_02ST: LIFTER  상승 Sen", rtb: "" },
{ device: "X7A5", comment: "R_03ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7A6", comment: "R_03ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7A7", comment: "R_03ST: LIFTER  하강 Sen", rtb: "" },
{ device: "X7A8", comment: "R_03ST: LIFTER  상승 Sen", rtb: "" },
{ device: "X7A9", comment: "R_04ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7AA", comment: "R_05ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7AB", comment: "R_04ST: T/TABLE 하강 Sen", rtb: "" },
{ device: "X7AC", comment: "R_04ST: T/TABLE 상승 Sen", rtb: "" },
{ device: "X7AD", comment: "R_04ST: T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X7AE", comment: "R_04ST: T/TABLE 회전단  Sen", rtb: "" },
{ device: "X7AF", comment: "R_05ST  AIR     SUPPLY  후진 Sen", rtb: "" },
{ device: "X7B0", comment: "R_06ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7B1", comment: "R_06ST: LIFTER  하강 Sen", rtb: "" },
{ device: "X7B2", comment: "R_06ST: LIFTER  상승 Sen", rtb: "" },
{ device: "X7B4", comment: "R_07ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7B5", comment: "R_08ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7B6", comment: "R_06ST: PALLET  도착 Sen", rtb: "" },
{ device: "X7BC", comment: "R_02ST: 원점복귀SW", rtb: "" },
{ device: "X7BD", comment: "R_03ST: 원점복귀SW", rtb: "" },
{ device: "X7BE", comment: "R_05ST: 원점복귀SW", rtb: "" },
{ device: "X7BF", comment: "R_06ST: 원점복귀SW", rtb: "" },
{ device: "X80", comment: "CYCLE   TIME    100의   자리", rtb: "" },
{ device: "X800", comment: "R_09ST: MODE    자동 SW", rtb: "" },
{ device: "X801", comment: "R_09ST: D/V 모터정회전  SW", rtb: "" },
{ device: "X802", comment: "R_09ST: LIFTER  하강 SW", rtb: "" },
{ device: "X803", comment: "R_09ST: LIFTER  상승 SW", rtb: "" },
{ device: "X804", comment: "리워크  라인    재입고  S/W", rtb: "" },
{ device: "X805", comment: "R_10ST: MODE    자동 SW", rtb: "" },
{ device: "X806", comment: "R_10ST: T/TABLE 하강 SW", rtb: "" },
{ device: "X807", comment: "R_10ST: T/TABLE 상승 SW", rtb: "" },
{ device: "X808", comment: "R_12ST: MODE    자동 SW", rtb: "" },
{ device: "X809", comment: "R_12ST: LIFTER  하강 SW", rtb: "" },
{ device: "X80A", comment: "R_12ST: LIFTER  상승 SW", rtb: "" },
{ device: "X80B", comment: "R_12ST  AIR     UNCLAMP 후진 SW", rtb: "" },
{ device: "X80C", comment: "R_12ST: AIR     UNCLAMP 전진 SW", rtb: "" },
{ device: "X80D", comment: "R_12ST: AIR     SUPPLY  후진 SW", rtb: "" },
{ device: "X80E", comment: "R_12ST: AIR     SUPPLY  전진 SW", rtb: "" },
{ device: "X80F", comment: "R_12ST: AIR     SUPPLY  ON SW", rtb: "" },
{ device: "X810", comment: "R_11ST: 락킹    1 CYCLE SW", rtb: "" },
{ device: "X811", comment: "R_12ST: 언락킹  1 CYCLE SW", rtb: "" },
{ device: "X812", comment: "R_11ST: MODE    자동SW", rtb: "" },
{ device: "X813", comment: "R_11ST: PASS SW", rtb: "" },
{ device: "X814", comment: "R_11ST: T/TABLE 상승SW", rtb: "" },
{ device: "X815", comment: "R_11ST: T/TABLE 하강 SW", rtb: "" },
{ device: "X816", comment: "R_13ST: MODE    자동 SW", rtb: "" },
{ device: "X817", comment: "R_13ST: T/TABLE 하강 SW", rtb: "" },
{ device: "X818", comment: "R_13ST: T/TABLE 상승 SW", rtb: "" },
{ device: "X819", comment: "R_13ST: T/TABLE 복귀단  SW", rtb: "" },
{ device: "X81A", comment: "R_13ST: T/TABLE 회전단  SW", rtb: "" },
{ device: "X81B", comment: "R_13ST  배출요구SW", rtb: "" },
{ device: "X81C", comment: "R_10ST: PASS SW", rtb: "" },
{ device: "X81D", comment: "R_10ST: 작업완료SW", rtb: "" },
{ device: "X81E", comment: "R_11ST: 작업완료S/W", rtb: "" },
{ device: "X81F", comment: "R_11ST: AIR     SUPPLY  ON SW", rtb: "" },
{ device: "X820", comment: "R_09ST: PALLET  도착 Sen", rtb: "" },
{ device: "X821", comment: "R_09ST: PALLET  도착 Sen", rtb: "" },
{ device: "X822", comment: "R_09ST: LIFTER  하강 Sen", rtb: "" },
{ device: "X823", comment: "R_09ST: LIFTER  상승 Sen", rtb: "" },
{ device: "X824", comment: "R_10ST: PALLET  도착 Sen", rtb: "" },
{ device: "X825", comment: "R_10ST: T/TABLE 하강 Sen", rtb: "" },
{ device: "X826", comment: "R_10ST: T/TABLE 상승 Sen", rtb: "" },
{ device: "X827", comment: "R_10ST: T/TABLE 0도 감지", rtb: "" },
{ device: "X828", comment: "R_10ST: T/TABLE 180도   감지", rtb: "" },
{ device: "X829", comment: "R_11ST: PALLET  도착 Sen", rtb: "" },
{ device: "X82A", comment: "R_11ST: PALLET  도착 Sen", rtb: "" },
{ device: "X82B", comment: "R_11ST: LIFTER  하강 Sen", rtb: "" },
{ device: "X82C", comment: "R_11ST: AIR     SUPPLY  후진 Sen", rtb: "" },
{ device: "X82D", comment: "R_11ST: LH AIR  SUPPLY  후진 Sen", rtb: "" },
{ device: "X82E", comment: "R_12ST: 인타운OK신호", rtb: "" },
{ device: "X82F", comment: "R_11ST: 인타운  작업결과OK", rtb: "" },
{ device: "X830", comment: "R_12ST: PALLET  도착 Sen", rtb: "" },
{ device: "X831", comment: "R_12ST: LH 사양 감지", rtb: "" },
{ device: "X832", comment: "R_12ST: RH 사양 감지", rtb: "" },
{ device: "X833", comment: "R_11ST: LIFTER  하강 Se", rtb: "" },
{ device: "X834", comment: "R_11ST: LIFTER  상승 Sen", rtb: "" },
{ device: "X835", comment: "R_13ST: PALLET  도착단", rtb: "" },
{ device: "X836", comment: "R_13ST: T/TABLE 하강단", rtb: "" },
{ device: "X837", comment: "R_13ST: T/TABLE 상승단", rtb: "" },
{ device: "X838", comment: "R_13ST: T/TABLE 복귀단  Sen", rtb: "" },
{ device: "X839", comment: "R_13ST: T/TABLE 회전단  Sen", rtb: "" },
{ device: "X83A", comment: "R_11ST  AIR     UNCLMAP 후진단", rtb: "" },
{ device: "X83B", comment: "R_06ST: 원점복귀SW", rtb: "" },
{ device: "X83C", comment: "R_11ST: 디버터  상승단", rtb: "" },
{ device: "X83D", comment: "R_11ST: 디버터  상승단", rtb: "" },
{ device: "X83E", comment: "R_11ST: 디버터  회전단", rtb: "" },
{ device: "X83F", comment: "R_11ST: 디버터  복귀단", rtb: "" },
{ device: "X84", comment: "CYCLE   TIME    10의 자리", rtb: "" },
{ device: "X860", comment: "60ST:   폴딩장비자동S/W", rtb: "" },
{ device: "X861", comment: "60ST:   폴딩장비PASS    S/W", rtb: "" },
{ device: "X862", comment: "60ST:   폴딩장비레버    전진S/W", rtb: "" },
{ device: "X863", comment: "60ST:   폴딩장비레버    후진S/W", rtb: "" },
{ device: "X864", comment: "60ST:   폴딩장비레버좌측회전S/W", rtb: "" },
{ device: "X865", comment: "60ST:   폴딩장비레버우측회전S/W", rtb: "" },
{ device: "X866", comment: "60ST:   폴딩장비레버    상승S/W", rtb: "" },
{ device: "X867", comment: "60ST:   폴딩장비레버    하강S/W", rtb: "" },
{ device: "X86A", comment: "60ST:   폴딩장비푸셔    좌측S/W", rtb: "" },
{ device: "X86B", comment: "60ST:   폴딩장비푸셔    우측S/W", rtb: "" },
{ device: "X86C", comment: "60ST:   폴딩장비푸셔    후진S/W", rtb: "" },
{ device: "X86D", comment: "60ST:   폴딩장비푸셔    전진S/W", rtb: "" },
{ device: "X86E", comment: "60ST:   폴딩장비수동S/W", rtb: "" },
{ device: "X870", comment: "LH Unit 전진", rtb: "" },
{ device: "X871", comment: "LH Unit 후진-   IO없음", rtb: "" },
{ device: "X872", comment: "LH Unit 좌/우   후진-   IO없음", rtb: "" },
{ device: "X873", comment: "LH Unit 좌/우   전진", rtb: "" },
{ device: "X874", comment: "LH Unit 상승", rtb: "" },
{ device: "X875", comment: "LH Unit 하강-   IO없음", rtb: "" },
{ device: "X878", comment: "60ST:   폴딩장비레버    전진단", rtb: "" },
{ device: "X879", comment: "60ST:   폴딩장비레버    후진단", rtb: "" },
{ device: "X87A", comment: "60ST:폴딩장비레버우측작업확인단", rtb: "" },
{ device: "X87B", comment: "60ST:폴딩장비레버좌측원점확인단", rtb: "" },
{ device: "X87C", comment: "60ST:   폴딩장비레버    상승단", rtb: "" },
{ device: "X87D", comment: "60ST:   폴딩장비레버    하강단", rtb: "" },
{ device: "X88", comment: "CYCLE   TIME    1의 자리", rtb: "" },
{ device: "X880", comment: "68ST:   폴딩장비자동S/W", rtb: "" },
{ device: "X881", comment: "수동    Pass S/W", rtb: "" },
{ device: "X882", comment: "68ST:   폴딩장비레버    전진S/W", rtb: "" },
{ device: "X883", comment: "68ST:   폴딩장비레버    후진S/W", rtb: "" },
{ device: "X884", comment: "68ST:폴딩장비레버우측작업이동S/W", rtb: "" },
{ device: "X885", comment: "68ST:폴딩장비레버좌측원점이동S/W", rtb: "" },
{ device: "X886", comment: "68ST:   폴딩장비레버    상승S/W", rtb: "" },
{ device: "X887", comment: "68ST:   폴딩장비레버    하강S/W", rtb: "" },
{ device: "X88A", comment: "68ST:   폴딩장비푸셔좌측이동S/W", rtb: "" },
{ device: "X88B", comment: "68ST:   폴딩장비푸셔우측이동S/W", rtb: "" },
{ device: "X88C", comment: "68ST:   폴딩장비푸셔    후진S/W", rtb: "" },
{ device: "X88D", comment: "68ST:   폴딩장비푸셔    전진S/W", rtb: "" },
{ device: "X88E", comment: "68ST:   폴딩장비원점복귀S/W", rtb: "" },
{ device: "X88F", comment: "Remote  Box_10  CP Trip", rtb: "" },
{ device: "X890", comment: "LH Unit 전진", rtb: "" },
{ device: "X891", comment: "LH Unit 후진    - IO없음", rtb: "" },
{ device: "X892", comment: "LH Unit 좌/우   후진    -IO없음", rtb: "" },
{ device: "X893", comment: "LH Unit 좌/우   전진", rtb: "" },
{ device: "X894", comment: "LH Unit 상승", rtb: "" },
{ device: "X895", comment: "LH Unit 하강    -IO없음", rtb: "" },
{ device: "X898", comment: "68ST:   폴딩장비레버    전진단", rtb: "" },
{ device: "X899", comment: "68ST:   폴딩장비레버    후진단", rtb: "" },
{ device: "X89A", comment: "68ST:   폴딩장비레버좌측확인단", rtb: "" },
{ device: "X89B", comment: "68ST:폴딩장비레버좌측원점확인단", rtb: "" },
{ device: "X89C", comment: "68ST:   폴딩장비레버    상승단", rtb: "" },
{ device: "X89D", comment: "68ST:   폴딩장비레버    하강단", rtb: "" },
{ device: "X8E0", comment: "60ST:   폴딩장비푸셔 좌측확인단", rtb: "" },
{ device: "X8E1", comment: "60ST:   폴딩장비푸셔 우측확인단", rtb: "" },
{ device: "X8E2", comment: "60ST:   폴딩장비푸셔    전진단", rtb: "" },
{ device: "X8E3", comment: "60ST:   폴딩장비푸셔    후진단", rtb: "" },
{ device: "X8F0", comment: "푸셔Unit좌", rtb: "" },
{ device: "X8F1", comment: "푸셔Unit우", rtb: "" },
{ device: "X8F2", comment: "푸셔전진", rtb: "" },
{ device: "X8F3", comment: "68ST:   폴딩장비푸셔    후진단", rtb: "" },
{ device: "X900", comment: "01ST:   원점복귀SW", rtb: "" },
{ device: "X901", comment: "02ST:   원점복귀SW", rtb: "" },
{ device: "X902", comment: "05ST:   원점완료SW", rtb: "" },
{ device: "X903", comment: "06ST:   원점완료SW", rtb: "" },
{ device: "X904", comment: "09ST:   원점완료SW", rtb: "" },
{ device: "X905", comment: "01ST:   PALLET  투입배출SW", rtb: "" },
{ device: "X906", comment: "01ST:   투입배출MODE    완료", rtb: "" },
{ device: "X907", comment: "03ST:   서열패스SW", rtb: "" },
{ device: "X908", comment: "04ST:   서열패스SW", rtb: "" },
{ device: "X909", comment: "07ST:   서열패스SW/     사용안함", rtb: "" },
{ device: "X90A", comment: "05ST:   AIR     SUPPLY  후진 SW", rtb: "" },
{ device: "X90B", comment: "05ST:   AIR     SUPPLY  전진 SW", rtb: "" },
{ device: "X90C", comment: "05ST:   AIR     SUPPLY  ON SW", rtb: "" },
{ device: "X90D", comment: "05ST:   AIR     SUPPLY  반자동SW", rtb: "" },
{ device: "X90F", comment: "09ST:   비상정지RPB", rtb: "" },
{ device: "X920", comment: "11ST:   원점완료SW", rtb: "" },
{ device: "X921", comment: "15ST:   원점복귀S/W", rtb: "" },
{ device: "X922", comment: "20ST:   원점완료SW", rtb: "" },
{ device: "X923", comment: "26ST:   원점완료SW", rtb: "" },
{ device: "X924", comment: "20ST:   서열패스", rtb: "" },
{ device: "X925", comment: "인타운  ->20ST  서열작업완료", rtb: "" },
{ device: "X928", comment: "B/S 로봇-> C/V  작업완료(Y61)", rtb: "" },
{ device: "X929", comment: "B/S 로봇-> C/V  간섭없음(Y60)", rtb: "" },
{ device: "X92A", comment: "B/S 로봇-> C/V  로봇기동중(Y63)", rtb: "" },
{ device: "X92C", comment: "Back C/V-> 15ST 제품있음-YD8", rtb: "" },
{ device: "X940", comment: "31ST:   원점완료SW", rtb: "" },
{ device: "X941", comment: "38ST:   원점완료SW", rtb: "" },
{ device: "X942", comment: "39ST:   수동/자동S/W", rtb: "" },
{ device: "X943", comment: "47ST:   원점복귀SW", rtb: "" },
{ device: "X944", comment: "39ST:   LIFTER  하강 S/W", rtb: "" },
{ device: "X945", comment: "39ST:   LIFTER  상승 S/W", rtb: "" },
{ device: "X946", comment: "39ST:   TILT    하강 S/W", rtb: "" },
{ device: "X947", comment: "39ST:   TILT    상승 S/W", rtb: "" },
{ device: "X948", comment: "31ST:   1 CYCLE SW", rtb: "" },
{ device: "X949", comment: "39ST:   작업완료SW", rtb: "" },
{ device: "X94A", comment: "39ST:   PASS    S/W", rtb: "" },
{ device: "X94B", comment: "39ST:   원점복귀 S/W", rtb: "" },
{ device: "X94C", comment: "38ST:   1 CYCLE SW", rtb: "" },
{ device: "X94D", comment: "29ST:   작업완료SW", rtb: "" },
{ device: "X94E", comment: "47ST:   1 CYCLE SW", rtb: "" },
{ device: "X960", comment: "63ST:   비상정지RPB", rtb: "" },
{ device: "X961", comment: "58ST:   원점복귀SW", rtb: "" },
{ device: "X962", comment: "59ST:   원점복귀SW", rtb: "" },
{ device: "X963", comment: "60ST:   원점복귀SW", rtb: "" },
{ device: "X964", comment: "61ST:   원점복귀SW", rtb: "" },
{ device: "X965", comment: "64ST:   원점복귀SW", rtb: "" },
{ device: "X968", comment: "인타운  ->40ST  서열작업완료", rtb: "" },
{ device: "X969", comment: "58ST:   서열패스SW", rtb: "" },
{ device: "X96A", comment: "58ST:   PASS SW", rtb: "" },
{ device: "X96B", comment: "58ST:   작업완료SW", rtb: "" },
{ device: "X96C", comment: "60ST:   PASS S/W", rtb: "" },
{ device: "X96D", comment: "59ST:   TILT하강PB", rtb: "" },
{ device: "X96E", comment: "59ST:   1 CYCLE SW", rtb: "" },
{ device: "X96F", comment: "59ST:   TILT상승PB", rtb: "" },
{ device: "X980", comment: "66ST:   원점복귀SW", rtb: "" },
{ device: "X981", comment: "62ST:   원점복귀SW", rtb: "" },
{ device: "X982", comment: "71ST:   원점복귀SW", rtb: "" },
{ device: "X983", comment: "65ST:   원점복귀SW", rtb: "" },
{ device: "X984", comment: "75ST:   원점복귀SW", rtb: "" },
{ device: "X986", comment: "62ST:   1 CYCLE SW", rtb: "" },
{ device: "X987", comment: "69ST:   1 CYCLE SW", rtb: "" },
{ device: "X988", comment: "69ST:   1 CYCLE SW", rtb: "" },
{ device: "X989", comment: "73ST:   PASS SW", rtb: "" },
{ device: "X98A", comment: "71ST:   LH 제품 감지 Sen", rtb: "" },
{ device: "X98B", comment: "71ST:   RH 제품 감지 Sen", rtb: "" },
{ device: "X98C", comment: "73ST:   LH 제품 감지", rtb: "" },
{ device: "X98D", comment: "73ST:   RH 제품 감지", rtb: "" },
{ device: "X98E", comment: "73ST:   수동 S/W", rtb: "" },
{ device: "X98F", comment: "75ST:   OFF-자동ON- 수동 S/W", rtb: "" },
{ device: "X9A2", comment: "79ST:   원점복귀SW", rtb: "" },
{ device: "X9A3", comment: "87ST:   원점복귀SW", rtb: "" },
{ device: "X9A4", comment: "79ST:   1 CYCLE SW", rtb: "" },
{ device: "X9A5", comment: "79ST:   작업완료", rtb: "" },
{ device: "X9A6", comment: "87ST:   1 CYCLE SW", rtb: "" },
{ device: "X9A8", comment: "71ST:   히팅부스작업완료", rtb: "" },
{ device: "X9A9", comment: "78ST:   히팅부스작업완료", rtb: "" },
{ device: "X9AA", comment: "히팅부스->69ST   작업완료", rtb: "" },
{ device: "X9AC", comment: "60ST히팅-> C/V  작업중", rtb: "" },
{ device: "X9AE", comment: "76ST:   비상정지RPB", rtb: "" },
{ device: "X9AF", comment: "85ST:   비상정지RPB", rtb: "" },
{ device: "X9C0", comment: "86ST:   원점완료SW", rtb: "" },
{ device: "X9C1", comment: "88ST:   원점복귀SW", rtb: "" },
{ device: "X9C2", comment: "89ST:   원점복귀SW", rtb: "" },
{ device: "X9C3", comment: "90ST:   원점복귀SW", rtb: "" },
{ device: "X9C4", comment: "92ST:   원점복귀SW", rtb: "" },
{ device: "X9C5", comment: "93ST:   원점복귀SW", rtb: "" },
{ device: "X9C6", comment: "94ST:   원점복귀SW", rtb: "" },
{ device: "X9C7", comment: "86ST:   서열PASSSW", rtb: "" },
{ device: "X9C8", comment: "86ST:   1 CYCLE SW", rtb: "" },
{ device: "X9C9", comment: "94ST:   1 CYCLE SW", rtb: "" },
{ device: "X9CA", comment: "86ST:   상위서열완료", rtb: "" },
{ device: "X9CB", comment: "92ST:   PASS SW", rtb: "" },
{ device: "X9CC", comment: "91ST:   MODE    자동 SW", rtb: "" },
{ device: "X9CD", comment: "91ST:   LIFTER  하강 SW", rtb: "" },
{ device: "X9CE", comment: "91ST:   LIFTER  상승 SW", rtb: "" },
{ device: "X9CF", comment: "91ST:   원점복귀SW", rtb: "" },
{ device: "X9DE", comment: "92ST:   AIR     SUPPLY  ON SOL", rtb: "" },
{ device: "X9E0", comment: "2ST:    인타운  서열쓰기완료", rtb: "" },
{ device: "X9E3", comment: "91ST:   로봇안전센서", rtb: "" },
{ device: "X9E4", comment: "상차로봇[y61]   -> C/V  작업완료", rtb: "" },
{ device: "X9E5", comment: "상차로봇-> C/V  간섭없음", rtb: "" },
{ device: "X9E7", comment: "05ST로봇->C/V   기동중", rtb: "" },
{ device: "X9EA", comment: "트랙    로보트  안전센서감지", rtb: "" },
{ device: "X9EC", comment: "로보트  안전센서감지-메인 입구", rtb: "" },
{ device: "X9ED", comment: "인타운  ->3ST CV서열작업완료", rtb: "" },
{ device: "X9EE", comment: "인타운  ->4ST CV서열작업완료", rtb: "" },
{ device: "X9EF", comment: "인타운->7ST 서열작업완료상시on", rtb: "" },

];
